# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AlertRuleSlackNotificationArgs', 'AlertRuleSlackNotification']

@pulumi.input_type
class AlertRuleSlackNotificationArgs:
    def __init__(__self__, *,
                 alert_rule_id: pulumi.Input[_builtins.str],
                 slack_channel_id: pulumi.Input[_builtins.str],
                 minimum_severity_level: Optional[pulumi.Input[_builtins.str]] = None,
                 slack_installation_id: Optional[pulumi.Input[_builtins.str]] = None,
                 team_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a AlertRuleSlackNotification resource.

        :param pulumi.Input[_builtins.str] alert_rule_id: The ID of the alert rule. Use `ar_default` to manage a notification destination for the team's default rule.
        :param pulumi.Input[_builtins.str] slack_channel_id: The ID of the Slack channel.
        :param pulumi.Input[_builtins.str] minimum_severity_level: Set to `critical` to notify this destination only when an alert is classified as Critical. For custom alert rules, Critical is assigned after the agent investigation completes. Omit to notify this destination at every severity.
        :param pulumi.Input[_builtins.str] slack_installation_id: The ID of the completed Slack integration installation that owns the channel. It can be omitted when the team has exactly one completed Slack installation; the resolved ID is then stored in state. It must be configured when the team has multiple Slack installations.
        :param pulumi.Input[_builtins.str] team_id: The ID of the team that owns the alert rule and notification destination. Required if a default team is not configured in the provider.
        """
        pulumi.set(__self__, "alert_rule_id", alert_rule_id)
        pulumi.set(__self__, "slack_channel_id", slack_channel_id)
        if minimum_severity_level is not None:
            pulumi.set(__self__, "minimum_severity_level", minimum_severity_level)
        if slack_installation_id is not None:
            pulumi.set(__self__, "slack_installation_id", slack_installation_id)
        if team_id is not None:
            pulumi.set(__self__, "team_id", team_id)

    @_builtins.property
    @pulumi.getter(name="alertRuleId")
    def alert_rule_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the alert rule. Use `ar_default` to manage a notification destination for the team's default rule.
        """
        return pulumi.get(self, "alert_rule_id")

    @alert_rule_id.setter
    def alert_rule_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "alert_rule_id", value)

    @_builtins.property
    @pulumi.getter(name="slackChannelId")
    def slack_channel_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the Slack channel.
        """
        return pulumi.get(self, "slack_channel_id")

    @slack_channel_id.setter
    def slack_channel_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "slack_channel_id", value)

    @_builtins.property
    @pulumi.getter(name="minimumSeverityLevel")
    def minimum_severity_level(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Set to `critical` to notify this destination only when an alert is classified as Critical. For custom alert rules, Critical is assigned after the agent investigation completes. Omit to notify this destination at every severity.
        """
        return pulumi.get(self, "minimum_severity_level")

    @minimum_severity_level.setter
    def minimum_severity_level(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "minimum_severity_level", value)

    @_builtins.property
    @pulumi.getter(name="slackInstallationId")
    def slack_installation_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the completed Slack integration installation that owns the channel. It can be omitted when the team has exactly one completed Slack installation; the resolved ID is then stored in state. It must be configured when the team has multiple Slack installations.
        """
        return pulumi.get(self, "slack_installation_id")

    @slack_installation_id.setter
    def slack_installation_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "slack_installation_id", value)

    @_builtins.property
    @pulumi.getter(name="teamId")
    def team_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the team that owns the alert rule and notification destination. Required if a default team is not configured in the provider.
        """
        return pulumi.get(self, "team_id")

    @team_id.setter
    def team_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "team_id", value)


@pulumi.input_type
class _AlertRuleSlackNotificationState:
    def __init__(__self__, *,
                 alert_rule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 minimum_severity_level: Optional[pulumi.Input[_builtins.str]] = None,
                 slack_channel_id: Optional[pulumi.Input[_builtins.str]] = None,
                 slack_installation_id: Optional[pulumi.Input[_builtins.str]] = None,
                 team_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering AlertRuleSlackNotification resources.

        :param pulumi.Input[_builtins.str] alert_rule_id: The ID of the alert rule. Use `ar_default` to manage a notification destination for the team's default rule.
        :param pulumi.Input[_builtins.str] minimum_severity_level: Set to `critical` to notify this destination only when an alert is classified as Critical. For custom alert rules, Critical is assigned after the agent investigation completes. Omit to notify this destination at every severity.
        :param pulumi.Input[_builtins.str] slack_channel_id: The ID of the Slack channel.
        :param pulumi.Input[_builtins.str] slack_installation_id: The ID of the completed Slack integration installation that owns the channel. It can be omitted when the team has exactly one completed Slack installation; the resolved ID is then stored in state. It must be configured when the team has multiple Slack installations.
        :param pulumi.Input[_builtins.str] team_id: The ID of the team that owns the alert rule and notification destination. Required if a default team is not configured in the provider.
        """
        if alert_rule_id is not None:
            pulumi.set(__self__, "alert_rule_id", alert_rule_id)
        if minimum_severity_level is not None:
            pulumi.set(__self__, "minimum_severity_level", minimum_severity_level)
        if slack_channel_id is not None:
            pulumi.set(__self__, "slack_channel_id", slack_channel_id)
        if slack_installation_id is not None:
            pulumi.set(__self__, "slack_installation_id", slack_installation_id)
        if team_id is not None:
            pulumi.set(__self__, "team_id", team_id)

    @_builtins.property
    @pulumi.getter(name="alertRuleId")
    def alert_rule_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the alert rule. Use `ar_default` to manage a notification destination for the team's default rule.
        """
        return pulumi.get(self, "alert_rule_id")

    @alert_rule_id.setter
    def alert_rule_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "alert_rule_id", value)

    @_builtins.property
    @pulumi.getter(name="minimumSeverityLevel")
    def minimum_severity_level(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Set to `critical` to notify this destination only when an alert is classified as Critical. For custom alert rules, Critical is assigned after the agent investigation completes. Omit to notify this destination at every severity.
        """
        return pulumi.get(self, "minimum_severity_level")

    @minimum_severity_level.setter
    def minimum_severity_level(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "minimum_severity_level", value)

    @_builtins.property
    @pulumi.getter(name="slackChannelId")
    def slack_channel_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the Slack channel.
        """
        return pulumi.get(self, "slack_channel_id")

    @slack_channel_id.setter
    def slack_channel_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "slack_channel_id", value)

    @_builtins.property
    @pulumi.getter(name="slackInstallationId")
    def slack_installation_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the completed Slack integration installation that owns the channel. It can be omitted when the team has exactly one completed Slack installation; the resolved ID is then stored in state. It must be configured when the team has multiple Slack installations.
        """
        return pulumi.get(self, "slack_installation_id")

    @slack_installation_id.setter
    def slack_installation_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "slack_installation_id", value)

    @_builtins.property
    @pulumi.getter(name="teamId")
    def team_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the team that owns the alert rule and notification destination. Required if a default team is not configured in the provider.
        """
        return pulumi.get(self, "team_id")

    @team_id.setter
    def team_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "team_id", value)


@pulumi.type_token("vercel:index/alertRuleSlackNotification:AlertRuleSlackNotification")
class AlertRuleSlackNotification(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alert_rule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 minimum_severity_level: Optional[pulumi.Input[_builtins.str]] = None,
                 slack_channel_id: Optional[pulumi.Input[_builtins.str]] = None,
                 slack_installation_id: Optional[pulumi.Input[_builtins.str]] = None,
                 team_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a link between a Vercel alert rule and one Slack channel.

        ## Example Usage

        ```python
        import pulumi
        import pulumiverse_vercel as vercel

        alerts = vercel.AlertRuleSlackNotification("alerts",
            alert_rule_id="ar_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            slack_channel_id="C0123456789")
        ```

        ## Destination requirements

        Each resource owns one link. Do not manage the same alert-rule and Slack destination pair in multiple Terraform resources or states.

        If the team has exactly one completed Slack installation, `slack_installation_id` can be omitted and the provider stores the installation selected by the API in state. Teams with multiple Slack installations must configure `slack_installation_id` explicitly. The Vercel bot must already be invited to private channels.

        The special `ar_default` alert rule ID is supported even though the default rule itself cannot be managed by `AlertRule`.

        ## Import

        The `pulumi import` command can be used, for example:

        If a default team is configured in the provider, import using:

        ```sh
        $ pulumi import vercel:index/alertRuleSlackNotification:AlertRuleSlackNotification alerts ar_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/icfg_xxxxxxxxxxxxxxxxxxxxxxxxxxxx/C0123456789
        ```

        Otherwise, prefix the import ID with the team ID:

        ```sh
        $ pulumi import vercel:index/alertRuleSlackNotification:AlertRuleSlackNotification alerts team_xxxxxxxxxxxxxxxxxxxxxxxx/ar_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/icfg_xxxxxxxxxxxxxxxxxxxxxxxxxxxx/C0123456789
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] alert_rule_id: The ID of the alert rule. Use `ar_default` to manage a notification destination for the team's default rule.
        :param pulumi.Input[_builtins.str] minimum_severity_level: Set to `critical` to notify this destination only when an alert is classified as Critical. For custom alert rules, Critical is assigned after the agent investigation completes. Omit to notify this destination at every severity.
        :param pulumi.Input[_builtins.str] slack_channel_id: The ID of the Slack channel.
        :param pulumi.Input[_builtins.str] slack_installation_id: The ID of the completed Slack integration installation that owns the channel. It can be omitted when the team has exactly one completed Slack installation; the resolved ID is then stored in state. It must be configured when the team has multiple Slack installations.
        :param pulumi.Input[_builtins.str] team_id: The ID of the team that owns the alert rule and notification destination. Required if a default team is not configured in the provider.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AlertRuleSlackNotificationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a link between a Vercel alert rule and one Slack channel.

        ## Example Usage

        ```python
        import pulumi
        import pulumiverse_vercel as vercel

        alerts = vercel.AlertRuleSlackNotification("alerts",
            alert_rule_id="ar_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            slack_channel_id="C0123456789")
        ```

        ## Destination requirements

        Each resource owns one link. Do not manage the same alert-rule and Slack destination pair in multiple Terraform resources or states.

        If the team has exactly one completed Slack installation, `slack_installation_id` can be omitted and the provider stores the installation selected by the API in state. Teams with multiple Slack installations must configure `slack_installation_id` explicitly. The Vercel bot must already be invited to private channels.

        The special `ar_default` alert rule ID is supported even though the default rule itself cannot be managed by `AlertRule`.

        ## Import

        The `pulumi import` command can be used, for example:

        If a default team is configured in the provider, import using:

        ```sh
        $ pulumi import vercel:index/alertRuleSlackNotification:AlertRuleSlackNotification alerts ar_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/icfg_xxxxxxxxxxxxxxxxxxxxxxxxxxxx/C0123456789
        ```

        Otherwise, prefix the import ID with the team ID:

        ```sh
        $ pulumi import vercel:index/alertRuleSlackNotification:AlertRuleSlackNotification alerts team_xxxxxxxxxxxxxxxxxxxxxxxx/ar_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/icfg_xxxxxxxxxxxxxxxxxxxxxxxxxxxx/C0123456789
        ```


        :param str resource_name: The name of the resource.
        :param AlertRuleSlackNotificationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AlertRuleSlackNotificationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alert_rule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 minimum_severity_level: Optional[pulumi.Input[_builtins.str]] = None,
                 slack_channel_id: Optional[pulumi.Input[_builtins.str]] = None,
                 slack_installation_id: Optional[pulumi.Input[_builtins.str]] = None,
                 team_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AlertRuleSlackNotificationArgs.__new__(AlertRuleSlackNotificationArgs)

            if alert_rule_id is None and not opts.urn:
                raise TypeError("Missing required property 'alert_rule_id'")
            __props__.__dict__["alert_rule_id"] = alert_rule_id
            __props__.__dict__["minimum_severity_level"] = minimum_severity_level
            if slack_channel_id is None and not opts.urn:
                raise TypeError("Missing required property 'slack_channel_id'")
            __props__.__dict__["slack_channel_id"] = slack_channel_id
            __props__.__dict__["slack_installation_id"] = slack_installation_id
            __props__.__dict__["team_id"] = team_id
        super(AlertRuleSlackNotification, __self__).__init__(
            'vercel:index/alertRuleSlackNotification:AlertRuleSlackNotification',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            alert_rule_id: Optional[pulumi.Input[_builtins.str]] = None,
            minimum_severity_level: Optional[pulumi.Input[_builtins.str]] = None,
            slack_channel_id: Optional[pulumi.Input[_builtins.str]] = None,
            slack_installation_id: Optional[pulumi.Input[_builtins.str]] = None,
            team_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'AlertRuleSlackNotification':
        """
        Get an existing AlertRuleSlackNotification resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] alert_rule_id: The ID of the alert rule. Use `ar_default` to manage a notification destination for the team's default rule.
        :param pulumi.Input[_builtins.str] minimum_severity_level: Set to `critical` to notify this destination only when an alert is classified as Critical. For custom alert rules, Critical is assigned after the agent investigation completes. Omit to notify this destination at every severity.
        :param pulumi.Input[_builtins.str] slack_channel_id: The ID of the Slack channel.
        :param pulumi.Input[_builtins.str] slack_installation_id: The ID of the completed Slack integration installation that owns the channel. It can be omitted when the team has exactly one completed Slack installation; the resolved ID is then stored in state. It must be configured when the team has multiple Slack installations.
        :param pulumi.Input[_builtins.str] team_id: The ID of the team that owns the alert rule and notification destination. Required if a default team is not configured in the provider.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AlertRuleSlackNotificationState.__new__(_AlertRuleSlackNotificationState)

        __props__.__dict__["alert_rule_id"] = alert_rule_id
        __props__.__dict__["minimum_severity_level"] = minimum_severity_level
        __props__.__dict__["slack_channel_id"] = slack_channel_id
        __props__.__dict__["slack_installation_id"] = slack_installation_id
        __props__.__dict__["team_id"] = team_id
        return AlertRuleSlackNotification(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="alertRuleId")
    def alert_rule_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the alert rule. Use `ar_default` to manage a notification destination for the team's default rule.
        """
        return pulumi.get(self, "alert_rule_id")

    @_builtins.property
    @pulumi.getter(name="minimumSeverityLevel")
    def minimum_severity_level(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Set to `critical` to notify this destination only when an alert is classified as Critical. For custom alert rules, Critical is assigned after the agent investigation completes. Omit to notify this destination at every severity.
        """
        return pulumi.get(self, "minimum_severity_level")

    @_builtins.property
    @pulumi.getter(name="slackChannelId")
    def slack_channel_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the Slack channel.
        """
        return pulumi.get(self, "slack_channel_id")

    @_builtins.property
    @pulumi.getter(name="slackInstallationId")
    def slack_installation_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the completed Slack integration installation that owns the channel. It can be omitted when the team has exactly one completed Slack installation; the resolved ID is then stored in state. It must be configured when the team has multiple Slack installations.
        """
        return pulumi.get(self, "slack_installation_id")

    @_builtins.property
    @pulumi.getter(name="teamId")
    def team_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the team that owns the alert rule and notification destination. Required if a default team is not configured in the provider.
        """
        return pulumi.get(self, "team_id")

