provider: vercel
template: external-bridged-provider
organization: pulumiverse
major-version: 3
providerDefaultBranch: main
upstreamProviderOrg: vercel
pulumiConvert: 1
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
plugins:
  - name: terraform
    version: "1.0.19"
    kind: converter
registryDocs: true
publishRegistry: false
goBuildParallelism: 2
autoMergeProviderUpgrades: true