provider: vercel
template: external-bridged-provider
organization: pulumiverse
major-version: 3
providerDefaultBranch: main
upstreamProviderOrg: vercel
pulumiConvert: 1
publish:
    cdn: false
registryDocs: true
publishRegistry: false
goBuildParallelism: 2
autoMergeProviderUpgrades: true
