provider: vercel
template: external-bridged-provider
organization: pulumiverse
major-version: 2
providerDefaultBranch: main
upstreamProviderOrg: vercel
pulumiConvert: 0
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
