provider: vercel
template: external-bridged-provider
organization: pulumiverse
major-version: 2
providerDefaultBranch: main
upstreamProviderOrg: vercel
pulumiConvert: 1
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
plugins:
  - name: terraform
    version: "1.0.19"
    kind: converter
toolVersions:
  go: "1.18.x"
registryDocs: true
