// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel
{
    /// <summary>
    /// Provides a project connection for a Vercel Blob store.
    /// 
    /// This resource links an existing Blob store to a project and manages the generated `BLOB_READ_WRITE_TOKEN` environment variable prefix and target environments.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Vercel = Pulumiverse.Vercel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Vercel.BlobStore("example", new()
    ///     {
    ///         Name = "example-blob-store",
    ///     });
    /// 
    ///     var exampleProject = new Vercel.Project("example", new()
    ///     {
    ///         Name = "example-blob-project",
    ///     });
    /// 
    ///     var exampleBlobProjectConnection = new Vercel.BlobProjectConnection("example", new()
    ///     {
    ///         BlobStoreId = example.Id,
    ///         ProjectId = exampleProject.Id,
    ///         Environments = new[]
    ///         {
    ///             "preview",
    ///             "production",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// If importing into a personal account, or with a team configured on
    /// the provider, use the Blob store id and connection id.
    /// 
    /// ```sh
    /// $ pulumi import vercel:index/blobProjectConnection:BlobProjectConnection example store_xxxxxxxxxxxxxxxxxx/spc_xxxxxxxxxxxxxxxxxx
    /// ```
    /// 
    /// Alternatively, you can import via the team_id, Blob store id, and connection id.
    /// 
    /// ```sh
    /// $ pulumi import vercel:index/blobProjectConnection:BlobProjectConnection example team_xxxxxxxxxxxxxxxxxxxxxxxx/store_xxxxxxxxxxxxxxxxxx/spc_xxxxxxxxxxxxxxxxxx
    /// ```
    /// </summary>
    [VercelResourceType("vercel:index/blobProjectConnection:BlobProjectConnection")]
    public partial class BlobProjectConnection : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the Blob store to connect.
        /// </summary>
        [Output("blobStoreId")]
        public Output<string> BlobStoreId { get; private set; } = null!;

        /// <summary>
        /// The prefix used for the generated Blob environment variable names.
        /// </summary>
        [Output("envVarPrefix")]
        public Output<string> EnvVarPrefix { get; private set; } = null!;

        /// <summary>
        /// The environments in which the generated Blob environment variables should be created.
        /// </summary>
        [Output("environments")]
        public Output<ImmutableArray<string>> Environments { get; private set; } = null!;

        /// <summary>
        /// The ID of the Vercel project to connect to the Blob store.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The generated environment variable name that contains the Blob read/write token.
        /// </summary>
        [Output("readWriteTokenEnvVarName")]
        public Output<string> ReadWriteTokenEnvVarName { get; private set; } = null!;

        /// <summary>
        /// The ID of the team that owns the Blob store and project. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Output("teamId")]
        public Output<string> TeamId { get; private set; } = null!;


        /// <summary>
        /// Create a BlobProjectConnection resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BlobProjectConnection(string name, BlobProjectConnectionArgs args, CustomResourceOptions? options = null)
            : base("vercel:index/blobProjectConnection:BlobProjectConnection", name, args ?? new BlobProjectConnectionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BlobProjectConnection(string name, Input<string> id, BlobProjectConnectionState? state = null, CustomResourceOptions? options = null)
            : base("vercel:index/blobProjectConnection:BlobProjectConnection", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BlobProjectConnection resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BlobProjectConnection Get(string name, Input<string> id, BlobProjectConnectionState? state = null, CustomResourceOptions? options = null)
        {
            return new BlobProjectConnection(name, id, state, options);
        }
    }

    public sealed class BlobProjectConnectionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Blob store to connect.
        /// </summary>
        [Input("blobStoreId", required: true)]
        public Input<string> BlobStoreId { get; set; } = null!;

        /// <summary>
        /// The prefix used for the generated Blob environment variable names.
        /// </summary>
        [Input("envVarPrefix")]
        public Input<string>? EnvVarPrefix { get; set; }

        [Input("environments")]
        private InputList<string>? _environments;

        /// <summary>
        /// The environments in which the generated Blob environment variables should be created.
        /// </summary>
        public InputList<string> Environments
        {
            get => _environments ?? (_environments = new InputList<string>());
            set => _environments = value;
        }

        /// <summary>
        /// The ID of the Vercel project to connect to the Blob store.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The ID of the team that owns the Blob store and project. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public BlobProjectConnectionArgs()
        {
        }
        public static new BlobProjectConnectionArgs Empty => new BlobProjectConnectionArgs();
    }

    public sealed class BlobProjectConnectionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Blob store to connect.
        /// </summary>
        [Input("blobStoreId")]
        public Input<string>? BlobStoreId { get; set; }

        /// <summary>
        /// The prefix used for the generated Blob environment variable names.
        /// </summary>
        [Input("envVarPrefix")]
        public Input<string>? EnvVarPrefix { get; set; }

        [Input("environments")]
        private InputList<string>? _environments;

        /// <summary>
        /// The environments in which the generated Blob environment variables should be created.
        /// </summary>
        public InputList<string> Environments
        {
            get => _environments ?? (_environments = new InputList<string>());
            set => _environments = value;
        }

        /// <summary>
        /// The ID of the Vercel project to connect to the Blob store.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        /// <summary>
        /// The generated environment variable name that contains the Blob read/write token.
        /// </summary>
        [Input("readWriteTokenEnvVarName")]
        public Input<string>? ReadWriteTokenEnvVarName { get; set; }

        /// <summary>
        /// The ID of the team that owns the Blob store and project. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public BlobProjectConnectionState()
        {
        }
        public static new BlobProjectConnectionState Empty => new BlobProjectConnectionState();
    }
}
