// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel
{
    /// <summary>
    /// Provides an Edge Config resource.
    /// 
    /// An Edge Config is a global data store that enables experimentation with feature flags, A/B testing, critical redirects, and more.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Vercel = Pulumiverse.Vercel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Vercel.EdgeConfig("example", new()
    ///     {
    ///         Name = "example",
    ///     });
    /// 
    ///     var exampleProject = new Vercel.Project("example", new()
    ///     {
    ///         Name = "edge-config-example",
    ///     });
    /// 
    ///     var exampleEdgeConfigToken = new Vercel.EdgeConfigToken("example", new()
    ///     {
    ///         EdgeConfigId = example.Id,
    ///         Label = "example token",
    ///     });
    /// 
    ///     var exampleProjectEnvironmentVariable = new Vercel.ProjectEnvironmentVariable("example", new()
    ///     {
    ///         ProjectId = exampleProject.Id,
    ///         Targets = new[]
    ///         {
    ///             "production",
    ///             "preview",
    ///             "development",
    ///         },
    ///         Key = "EDGE_CONFIG",
    ///         Value = exampleEdgeConfigToken.ConnectionString,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// If importing into a personal account, or with a team configured on
    /// 
    /// the provider, simply use the edge config id.
    /// 
    /// - edge_config_id can be found by navigating to the Edge Config in the Vercel UI. It should begin with `ecfg_`.
    /// 
    /// ```sh
    /// $ pulumi import vercel:index/edgeConfig:EdgeConfig example ecfg_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    /// ```
    /// 
    /// Alternatively, you can import via the team_id and edge_config_id.
    /// 
    /// - team_id can be found in the team `settings` tab in the Vercel UI.
    /// 
    /// - edge_config_id can be found by navigating to the Edge Config in the Vercel UI. It should begin with `ecfg_`.
    /// 
    /// ```sh
    /// $ pulumi import vercel:index/edgeConfig:EdgeConfig example team_xxxxxxxxxxxxxxxxxxxxxxxx/ecfg_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    /// ```
    /// </summary>
    [VercelResourceType("vercel:index/edgeConfig:EdgeConfig")]
    public partial class EdgeConfig : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name/slug of the Edge Config.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Output("teamId")]
        public Output<string> TeamId { get; private set; } = null!;


        /// <summary>
        /// Create a EdgeConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EdgeConfig(string name, EdgeConfigArgs? args = null, CustomResourceOptions? options = null)
            : base("vercel:index/edgeConfig:EdgeConfig", name, args ?? new EdgeConfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EdgeConfig(string name, Input<string> id, EdgeConfigState? state = null, CustomResourceOptions? options = null)
            : base("vercel:index/edgeConfig:EdgeConfig", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EdgeConfig resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EdgeConfig Get(string name, Input<string> id, EdgeConfigState? state = null, CustomResourceOptions? options = null)
        {
            return new EdgeConfig(name, id, state, options);
        }
    }

    public sealed class EdgeConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name/slug of the Edge Config.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public EdgeConfigArgs()
        {
        }
        public static new EdgeConfigArgs Empty => new EdgeConfigArgs();
    }

    public sealed class EdgeConfigState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name/slug of the Edge Config.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public EdgeConfigState()
        {
        }
        public static new EdgeConfigState Empty => new EdgeConfigState();
    }
}
