// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel
{
    public static class GetVcrRepository
    {
        /// <summary>
        /// Provides information about an existing Vercel Container Registry (VCR) Repository.
        /// 
        /// A VCR Repository belongs to a Vercel Project and stores container images that can be
        /// used by Vercel Functions and Vercel Sandbox.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Vercel = Pulumiverse.Vercel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Vercel.GetVcrRepository.Invoke(new()
        ///     {
        ///         ProjectId = "prj_xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ///         Name = "my-repository",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetVcrRepositoryResult> InvokeAsync(GetVcrRepositoryArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVcrRepositoryResult>("vercel:index/getVcrRepository:getVcrRepository", args ?? new GetVcrRepositoryArgs(), options.WithDefaults());

        /// <summary>
        /// Provides information about an existing Vercel Container Registry (VCR) Repository.
        /// 
        /// A VCR Repository belongs to a Vercel Project and stores container images that can be
        /// used by Vercel Functions and Vercel Sandbox.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Vercel = Pulumiverse.Vercel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Vercel.GetVcrRepository.Invoke(new()
        ///     {
        ///         ProjectId = "prj_xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ///         Name = "my-repository",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetVcrRepositoryResult> Invoke(GetVcrRepositoryInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVcrRepositoryResult>("vercel:index/getVcrRepository:getVcrRepository", args ?? new GetVcrRepositoryInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Provides information about an existing Vercel Container Registry (VCR) Repository.
        /// 
        /// A VCR Repository belongs to a Vercel Project and stores container images that can be
        /// used by Vercel Functions and Vercel Sandbox.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Vercel = Pulumiverse.Vercel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Vercel.GetVcrRepository.Invoke(new()
        ///     {
        ///         ProjectId = "prj_xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ///         Name = "my-repository",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetVcrRepositoryResult> Invoke(GetVcrRepositoryInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetVcrRepositoryResult>("vercel:index/getVcrRepository:getVcrRepository", args ?? new GetVcrRepositoryInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVcrRepositoryArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the repository.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// The ID of the existing Vercel Project the repository belongs to.
        /// </summary>
        [Input("projectId", required: true)]
        public string ProjectId { get; set; } = null!;

        /// <summary>
        /// The ID of the team the repository exists under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public string? TeamId { get; set; }

        public GetVcrRepositoryArgs()
        {
        }
        public static new GetVcrRepositoryArgs Empty => new GetVcrRepositoryArgs();
    }

    public sealed class GetVcrRepositoryInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the repository.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The ID of the existing Vercel Project the repository belongs to.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The ID of the team the repository exists under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public GetVcrRepositoryInvokeArgs()
        {
        }
        public static new GetVcrRepositoryInvokeArgs Empty => new GetVcrRepositoryInvokeArgs();
    }


    [OutputType]
    public sealed class GetVcrRepositoryResult
    {
        /// <summary>
        /// The ID of the VCR Repository.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the repository.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of the existing Vercel Project the repository belongs to.
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// The ID of the team the repository exists under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        public readonly string TeamId;
        /// <summary>
        /// The URL of the repository, composed of the owner slug, the project slug and the repository name (e.g. `vcr.vercel.com/team-slug/project-slug/repository-name`). Use it to push and pull images with Docker-compatible tooling.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private GetVcrRepositoryResult(
            string id,

            string name,

            string projectId,

            string teamId,

            string url)
        {
            Id = id;
            Name = name;
            ProjectId = projectId;
            TeamId = teamId;
            Url = url;
        }
    }
}
