// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel
{
    /// <summary>
    /// Provides a Vercel KMS Issuer resource.
    /// 
    /// &gt; **Note:** Vercel KMS is currently in beta. Its resources, data sources, and the underlying API may change in backwards-incompatible ways in future releases of the provider.
    /// 
    /// A KMS Issuer signs JSON Web Tokens (JWTs) and exposes a JWKS endpoint at
    /// `https://kms.vercel.com/{id}/jwks.json`. An initial signing key is created
    /// automatically; use `vercel.KmsSigningKey` to rotate keys and
    /// `vercel.KmsProjectGrant` to grant projects the ability to sign tokens.
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// If importing into a personal account, or with a team configured on
    /// the provider, simply use the issuer id.
    /// - IssuerId can be found via the vercel.KmsIssuer data source or the API.
    /// 
    /// ```sh
    /// $ pulumi import vercel:index/kmsIssuer:KmsIssuer example iss_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    /// ```
    /// 
    /// Alternatively, you can import via the TeamId and issuer id.
    /// - TeamId can be found in the team `Settings` tab in the Vercel UI.
    /// 
    /// ```sh
    /// $ pulumi import vercel:index/kmsIssuer:KmsIssuer example team_xxxxxxxxxxxxxxxxxxxxxxxx/iss_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    /// ```
    /// </summary>
    [VercelResourceType("vercel:index/kmsIssuer:KmsIssuer")]
    public partial class KmsIssuer : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The signing algorithm to use for the issuer. Defaults to `RS512`. Changing this forces a new issuer to be created.
        /// </summary>
        [Output("algorithm")]
        public Output<string> Algorithm { get; private set; } = null!;

        /// <summary>
        /// The time the issuer was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// A PEM-encoded private key to import for the issuer. When provided, the issuer's origin becomes `External` and the algorithm is inferred from the key. Changing this forces a new issuer to be created. This value is never returned by the API and cannot be recovered on import.
        /// </summary>
        [Output("importKey")]
        public Output<string?> ImportKey { get; private set; } = null!;

        /// <summary>
        /// The key ID (`Kid`) to assign to the imported key. Only valid when `ImportKey` is set. Changing this forces a new issuer to be created.
        /// </summary>
        [Output("importKeyId")]
        public Output<string?> ImportKeyId { get; private set; } = null!;

        /// <summary>
        /// Identifies the policy that manages this issuer, if any.
        /// </summary>
        [Output("managedBy")]
        public Output<string> ManagedBy { get; private set; } = null!;

        /// <summary>
        /// The name of the issuer.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The origin of the issuer's key material, either `Vercel` or `External`.
        /// </summary>
        [Output("origin")]
        public Output<string> Origin { get; private set; } = null!;

        /// <summary>
        /// The ID of the team that owns the issuer.
        /// </summary>
        [Output("ownerId")]
        public Output<string> OwnerId { get; private set; } = null!;

        /// <summary>
        /// The signing keys belonging to the issuer. Keys are created automatically and can be rotated with the `vercel.KmsSigningKey` resource.
        /// </summary>
        [Output("signingKeys")]
        public Output<ImmutableArray<Outputs.KmsIssuerSigningKey>> SigningKeys { get; private set; } = null!;

        /// <summary>
        /// The ID of the team the issuer should be created under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Output("teamId")]
        public Output<string> TeamId { get; private set; } = null!;

        /// <summary>
        /// The time the issuer was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a KmsIssuer resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public KmsIssuer(string name, KmsIssuerArgs? args = null, CustomResourceOptions? options = null)
            : base("vercel:index/kmsIssuer:KmsIssuer", name, args ?? new KmsIssuerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private KmsIssuer(string name, Input<string> id, KmsIssuerState? state = null, CustomResourceOptions? options = null)
            : base("vercel:index/kmsIssuer:KmsIssuer", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
                AdditionalSecretOutputs =
                {
                    "importKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing KmsIssuer resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static KmsIssuer Get(string name, Input<string> id, KmsIssuerState? state = null, CustomResourceOptions? options = null)
        {
            return new KmsIssuer(name, id, state, options);
        }
    }

    public sealed class KmsIssuerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The signing algorithm to use for the issuer. Defaults to `RS512`. Changing this forces a new issuer to be created.
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        [Input("importKey")]
        private Input<string>? _importKey;

        /// <summary>
        /// A PEM-encoded private key to import for the issuer. When provided, the issuer's origin becomes `External` and the algorithm is inferred from the key. Changing this forces a new issuer to be created. This value is never returned by the API and cannot be recovered on import.
        /// </summary>
        public Input<string>? ImportKey
        {
            get => _importKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _importKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The key ID (`Kid`) to assign to the imported key. Only valid when `ImportKey` is set. Changing this forces a new issuer to be created.
        /// </summary>
        [Input("importKeyId")]
        public Input<string>? ImportKeyId { get; set; }

        /// <summary>
        /// The name of the issuer.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the team the issuer should be created under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public KmsIssuerArgs()
        {
        }
        public static new KmsIssuerArgs Empty => new KmsIssuerArgs();
    }

    public sealed class KmsIssuerState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The signing algorithm to use for the issuer. Defaults to `RS512`. Changing this forces a new issuer to be created.
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        /// <summary>
        /// The time the issuer was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("importKey")]
        private Input<string>? _importKey;

        /// <summary>
        /// A PEM-encoded private key to import for the issuer. When provided, the issuer's origin becomes `External` and the algorithm is inferred from the key. Changing this forces a new issuer to be created. This value is never returned by the API and cannot be recovered on import.
        /// </summary>
        public Input<string>? ImportKey
        {
            get => _importKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _importKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The key ID (`Kid`) to assign to the imported key. Only valid when `ImportKey` is set. Changing this forces a new issuer to be created.
        /// </summary>
        [Input("importKeyId")]
        public Input<string>? ImportKeyId { get; set; }

        /// <summary>
        /// Identifies the policy that manages this issuer, if any.
        /// </summary>
        [Input("managedBy")]
        public Input<string>? ManagedBy { get; set; }

        /// <summary>
        /// The name of the issuer.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The origin of the issuer's key material, either `Vercel` or `External`.
        /// </summary>
        [Input("origin")]
        public Input<string>? Origin { get; set; }

        /// <summary>
        /// The ID of the team that owns the issuer.
        /// </summary>
        [Input("ownerId")]
        public Input<string>? OwnerId { get; set; }

        [Input("signingKeys")]
        private InputList<Inputs.KmsIssuerSigningKeyGetArgs>? _signingKeys;

        /// <summary>
        /// The signing keys belonging to the issuer. Keys are created automatically and can be rotated with the `vercel.KmsSigningKey` resource.
        /// </summary>
        public InputList<Inputs.KmsIssuerSigningKeyGetArgs> SigningKeys
        {
            get => _signingKeys ?? (_signingKeys = new InputList<Inputs.KmsIssuerSigningKeyGetArgs>());
            set => _signingKeys = value;
        }

        /// <summary>
        /// The ID of the team the issuer should be created under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        /// <summary>
        /// The time the issuer was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public KmsIssuerState()
        {
        }
        public static new KmsIssuerState Empty => new KmsIssuerState();
    }
}
