// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel
{
    /// <summary>
    /// Provides a client secret for a `vercel.OauthApp` ([Sign in with Vercel](https://vercel.com/docs/sign-in-with-vercel)).
    /// 
    /// The secret value is only ever returned by the API at creation time and is stored (marked sensitive) in the Terraform state. An OAuth App can have at most two client secrets at a time, so zero-downtime rotation is possible by creating a new secret before destroying the old one (e.g. with `pulumi up -replace` and `CreateBeforeDestroy`).
    /// 
    /// &gt; Managing client secrets requires the Owner role on the team.
    /// 
    /// &gt; This resource cannot be imported, as the API never re-exposes the secret value.
    /// </summary>
    [VercelResourceType("vercel:index/oauthAppClientSecret:OauthAppClientSecret")]
    public partial class OauthAppClientSecret : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The generated client secret. Only available at creation time; stored in the Terraform state.
        /// </summary>
        [Output("clientSecret")]
        public Output<string> ClientSecret { get; private set; } = null!;

        /// <summary>
        /// The last four characters of the client secret — the identifier the Vercel API and dashboard use to reference this secret.
        /// </summary>
        [Output("lastFourChars")]
        public Output<string> LastFourChars { get; private set; } = null!;

        /// <summary>
        /// The client ID of the OAuth App (`cl_...`) to generate a secret for.
        /// </summary>
        [Output("oauthAppId")]
        public Output<string> OauthAppId { get; private set; } = null!;

        /// <summary>
        /// The ID of the team the OAuth App exists under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Output("teamId")]
        public Output<string> TeamId { get; private set; } = null!;


        /// <summary>
        /// Create a OauthAppClientSecret resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OauthAppClientSecret(string name, OauthAppClientSecretArgs args, CustomResourceOptions? options = null)
            : base("vercel:index/oauthAppClientSecret:OauthAppClientSecret", name, args ?? new OauthAppClientSecretArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OauthAppClientSecret(string name, Input<string> id, OauthAppClientSecretState? state = null, CustomResourceOptions? options = null)
            : base("vercel:index/oauthAppClientSecret:OauthAppClientSecret", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
                AdditionalSecretOutputs =
                {
                    "clientSecret",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OauthAppClientSecret resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OauthAppClientSecret Get(string name, Input<string> id, OauthAppClientSecretState? state = null, CustomResourceOptions? options = null)
        {
            return new OauthAppClientSecret(name, id, state, options);
        }
    }

    public sealed class OauthAppClientSecretArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The client ID of the OAuth App (`cl_...`) to generate a secret for.
        /// </summary>
        [Input("oauthAppId", required: true)]
        public Input<string> OauthAppId { get; set; } = null!;

        /// <summary>
        /// The ID of the team the OAuth App exists under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public OauthAppClientSecretArgs()
        {
        }
        public static new OauthAppClientSecretArgs Empty => new OauthAppClientSecretArgs();
    }

    public sealed class OauthAppClientSecretState : global::Pulumi.ResourceArgs
    {
        [Input("clientSecret")]
        private Input<string>? _clientSecret;

        /// <summary>
        /// The generated client secret. Only available at creation time; stored in the Terraform state.
        /// </summary>
        public Input<string>? ClientSecret
        {
            get => _clientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The last four characters of the client secret — the identifier the Vercel API and dashboard use to reference this secret.
        /// </summary>
        [Input("lastFourChars")]
        public Input<string>? LastFourChars { get; set; }

        /// <summary>
        /// The client ID of the OAuth App (`cl_...`) to generate a secret for.
        /// </summary>
        [Input("oauthAppId")]
        public Input<string>? OauthAppId { get; set; }

        /// <summary>
        /// The ID of the team the OAuth App exists under. Required when configuring a team resource if a default team has not been set in the provider.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public OauthAppClientSecretState()
        {
        }
        public static new OauthAppClientSecretState Empty => new OauthAppClientSecretState();
    }
}
