// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumiverse.vercel.inputs.AuditLogDrainHttpArgs;
import com.pulumiverse.vercel.inputs.AuditLogDrainS3Args;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AuditLogDrainArgs extends com.pulumi.resources.ResourceArgs {

    public static final AuditLogDrainArgs Empty = new AuditLogDrainArgs();

    /**
     * Configuration for delivery to a custom HTTP endpoint. Exactly one of `http` or `s3` must be configured.
     * 
     */
    @Import(name="http")
    private @Nullable Output<AuditLogDrainHttpArgs> http;

    /**
     * @return Configuration for delivery to a custom HTTP endpoint. Exactly one of `http` or `s3` must be configured.
     * 
     */
    public Optional<Output<AuditLogDrainHttpArgs>> http() {
        return Optional.ofNullable(this.http);
    }

    /**
     * A human-readable name for the Audit Log Drain.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return A human-readable name for the Audit Log Drain.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Configuration for delivery to an Amazon S3 bucket. Exactly one of `http` or `s3` must be configured.
     * 
     */
    @Import(name="s3")
    private @Nullable Output<AuditLogDrainS3Args> s3;

    /**
     * @return Configuration for delivery to an Amazon S3 bucket. Exactly one of `http` or `s3` must be configured.
     * 
     */
    public Optional<Output<AuditLogDrainS3Args>> s3() {
        return Optional.ofNullable(this.s3);
    }

    /**
     * The ID of the team the Audit Log Drain should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return The ID of the team the Audit Log Drain should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    private AuditLogDrainArgs() {}

    private AuditLogDrainArgs(AuditLogDrainArgs $) {
        this.http = $.http;
        this.name = $.name;
        this.s3 = $.s3;
        this.teamId = $.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AuditLogDrainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AuditLogDrainArgs $;

        public Builder() {
            $ = new AuditLogDrainArgs();
        }

        public Builder(AuditLogDrainArgs defaults) {
            $ = new AuditLogDrainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param http Configuration for delivery to a custom HTTP endpoint. Exactly one of `http` or `s3` must be configured.
         * 
         * @return builder
         * 
         */
        public Builder http(@Nullable Output<AuditLogDrainHttpArgs> http) {
            $.http = http;
            return this;
        }

        /**
         * @param http Configuration for delivery to a custom HTTP endpoint. Exactly one of `http` or `s3` must be configured.
         * 
         * @return builder
         * 
         */
        public Builder http(AuditLogDrainHttpArgs http) {
            return http(Output.of(http));
        }

        /**
         * @param name A human-readable name for the Audit Log Drain.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A human-readable name for the Audit Log Drain.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param s3 Configuration for delivery to an Amazon S3 bucket. Exactly one of `http` or `s3` must be configured.
         * 
         * @return builder
         * 
         */
        public Builder s3(@Nullable Output<AuditLogDrainS3Args> s3) {
            $.s3 = s3;
            return this;
        }

        /**
         * @param s3 Configuration for delivery to an Amazon S3 bucket. Exactly one of `http` or `s3` must be configured.
         * 
         * @return builder
         * 
         */
        public Builder s3(AuditLogDrainS3Args s3) {
            return s3(Output.of(s3));
        }

        /**
         * @param teamId The ID of the team the Audit Log Drain should exist under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId The ID of the team the Audit Log Drain should exist under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        public AuditLogDrainArgs build() {
            return $;
        }
    }

}
