// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.vercel.AuditLogDrainArgs;
import com.pulumiverse.vercel.Utilities;
import com.pulumiverse.vercel.inputs.AuditLogDrainState;
import com.pulumiverse.vercel.outputs.AuditLogDrainHttp;
import com.pulumiverse.vercel.outputs.AuditLogDrainS3;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides an Audit Log Drain resource.
 * 
 * Audit Log Drains forward team activity events to an HTTP endpoint or Amazon S3. They apply to the whole team and do not support project selection, filtering, or sampling.
 * 
 * &gt; Audit Log Drains are only available to Enterprise teams.
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumiverse.vercel.AuditLogDrain;
 * import com.pulumiverse.vercel.AuditLogDrainArgs;
 * import com.pulumi.vercel.inputs.AuditLogDrainHttpArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new AuditLogDrain("example", AuditLogDrainArgs.builder()
 *             .name("security-audit-events")
 *             .http(AuditLogDrainHttpArgs.builder()
 *                 .endpoint("https://siem.example.com/vercel")
 *                 .encoding("ndjson")
 *                 .compression("gzip")
 *                 .headers(Map.of("Authorization", "Bearer my-secret-token"))
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * The `pulumi import` command can be used, for example:
 * 
 * If importing with a default team configured in the provider, simply use the
 * audit_log_drain_id.
 * 
 * ```sh
 * $ pulumi import vercel:index/auditLogDrain:AuditLogDrain example drn_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 * ```
 * 
 * Alternatively, import using team_id/audit_log_drain_id.
 * 
 * ```sh
 * $ pulumi import vercel:index/auditLogDrain:AuditLogDrain example team_xxxxxxxxxxxxxxxxxxxxxxxx/drn_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 * ```
 * 
 */
@ResourceType(type="vercel:index/auditLogDrain:AuditLogDrain")
public class AuditLogDrain extends com.pulumi.resources.CustomResource {
    /**
     * Configuration for delivery to a custom HTTP endpoint. Exactly one of `http` or `s3` must be configured.
     * 
     */
    @Export(name="http", refs={AuditLogDrainHttp.class}, tree="[0]")
    private Output</* @Nullable */ AuditLogDrainHttp> http;

    /**
     * @return Configuration for delivery to a custom HTTP endpoint. Exactly one of `http` or `s3` must be configured.
     * 
     */
    public Output<Optional<AuditLogDrainHttp>> http() {
        return Codegen.optional(this.http);
    }
    /**
     * A human-readable name for the Audit Log Drain.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return A human-readable name for the Audit Log Drain.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Configuration for delivery to an Amazon S3 bucket. Exactly one of `http` or `s3` must be configured.
     * 
     */
    @Export(name="s3", refs={AuditLogDrainS3.class}, tree="[0]")
    private Output</* @Nullable */ AuditLogDrainS3> s3;

    /**
     * @return Configuration for delivery to an Amazon S3 bucket. Exactly one of `http` or `s3` must be configured.
     * 
     */
    public Output<Optional<AuditLogDrainS3>> s3() {
        return Codegen.optional(this.s3);
    }
    /**
     * The ID of the team the Audit Log Drain should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Export(name="teamId", refs={String.class}, tree="[0]")
    private Output<String> teamId;

    /**
     * @return The ID of the team the Audit Log Drain should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Output<String> teamId() {
        return this.teamId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AuditLogDrain(java.lang.String name) {
        this(name, AuditLogDrainArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AuditLogDrain(java.lang.String name, @Nullable AuditLogDrainArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AuditLogDrain(java.lang.String name, @Nullable AuditLogDrainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vercel:index/auditLogDrain:AuditLogDrain", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private AuditLogDrain(java.lang.String name, Output<java.lang.String> id, @Nullable AuditLogDrainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vercel:index/auditLogDrain:AuditLogDrain", name, state, makeResourceOptions(options, id), false);
    }

    private static AuditLogDrainArgs makeArgs(@Nullable AuditLogDrainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AuditLogDrainArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AuditLogDrain get(java.lang.String name, Output<java.lang.String> id, @Nullable AuditLogDrainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AuditLogDrain(name, id, state, options);
    }
}
