// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.vercel.inputs.ProjectRoutePositionArgs;
import com.pulumiverse.vercel.inputs.ProjectRouteRouteArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectRouteArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectRouteArgs Empty = new ProjectRouteArgs();

    /**
     * An optional description of the rule.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return An optional description of the rule.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Whether the rule is enabled.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Whether the rule is enabled.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * A human-readable name for the rule.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return A human-readable name for the rule.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Where to insert the rule when it is created or replaced. This metadata is not returned by the API, so imported routes do not infer it.
     * 
     */
    @Import(name="position")
    private @Nullable Output<ProjectRoutePositionArgs> position;

    /**
     * @return Where to insert the rule when it is created or replaced. This metadata is not returned by the API, so imported routes do not infer it.
     * 
     */
    public Optional<Output<ProjectRoutePositionArgs>> position() {
        return Optional.ofNullable(this.position);
    }

    /**
     * The ID of the project to manage a routing rule for.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return The ID of the project to manage a routing rule for.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * The routing rule definition.
     * 
     */
    @Import(name="route", required=true)
    private Output<ProjectRouteRouteArgs> route;

    /**
     * @return The routing rule definition.
     * 
     */
    public Output<ProjectRouteRouteArgs> route() {
        return this.route;
    }

    /**
     * The source pattern syntax. You can usually omit this and let Vercel infer it from `route.src`.
     * 
     */
    @Import(name="srcSyntax")
    private @Nullable Output<String> srcSyntax;

    /**
     * @return The source pattern syntax. You can usually omit this and let Vercel infer it from `route.src`.
     * 
     */
    public Optional<Output<String>> srcSyntax() {
        return Optional.ofNullable(this.srcSyntax);
    }

    /**
     * The ID of the team the project exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return The ID of the team the project exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    private ProjectRouteArgs() {}

    private ProjectRouteArgs(ProjectRouteArgs $) {
        this.description = $.description;
        this.enabled = $.enabled;
        this.name = $.name;
        this.position = $.position;
        this.projectId = $.projectId;
        this.route = $.route;
        this.srcSyntax = $.srcSyntax;
        this.teamId = $.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectRouteArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectRouteArgs $;

        public Builder() {
            $ = new ProjectRouteArgs();
        }

        public Builder(ProjectRouteArgs defaults) {
            $ = new ProjectRouteArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description An optional description of the rule.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description An optional description of the rule.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param enabled Whether the rule is enabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether the rule is enabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param name A human-readable name for the rule.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A human-readable name for the rule.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param position Where to insert the rule when it is created or replaced. This metadata is not returned by the API, so imported routes do not infer it.
         * 
         * @return builder
         * 
         */
        public Builder position(@Nullable Output<ProjectRoutePositionArgs> position) {
            $.position = position;
            return this;
        }

        /**
         * @param position Where to insert the rule when it is created or replaced. This metadata is not returned by the API, so imported routes do not infer it.
         * 
         * @return builder
         * 
         */
        public Builder position(ProjectRoutePositionArgs position) {
            return position(Output.of(position));
        }

        /**
         * @param projectId The ID of the project to manage a routing rule for.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the project to manage a routing rule for.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param route The routing rule definition.
         * 
         * @return builder
         * 
         */
        public Builder route(Output<ProjectRouteRouteArgs> route) {
            $.route = route;
            return this;
        }

        /**
         * @param route The routing rule definition.
         * 
         * @return builder
         * 
         */
        public Builder route(ProjectRouteRouteArgs route) {
            return route(Output.of(route));
        }

        /**
         * @param srcSyntax The source pattern syntax. You can usually omit this and let Vercel infer it from `route.src`.
         * 
         * @return builder
         * 
         */
        public Builder srcSyntax(@Nullable Output<String> srcSyntax) {
            $.srcSyntax = srcSyntax;
            return this;
        }

        /**
         * @param srcSyntax The source pattern syntax. You can usually omit this and let Vercel infer it from `route.src`.
         * 
         * @return builder
         * 
         */
        public Builder srcSyntax(String srcSyntax) {
            return srcSyntax(Output.of(srcSyntax));
        }

        /**
         * @param teamId The ID of the team the project exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId The ID of the team the project exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        public ProjectRouteArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("ProjectRouteArgs", "projectId");
            }
            if ($.route == null) {
                throw new MissingRequiredPropertyException("ProjectRouteArgs", "route");
            }
            return $;
        }
    }

}
