// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FirewallConfigRulesRuleConditionGroupCondition {
    /**
     * @return Key within type to match against
     * 
     */
    private @Nullable String key;
    /**
     * @return Negate the condition. Defaults to false.
     * 
     */
    private @Nullable Boolean neg;
    /**
     * @return Operator to use for comparison. Options: `re` (regex), `eq` (equals), `neq` (not equals), `ex` (exists), `nex` (not exists), `inc` (includes), `ninc` (not includes), `pre` (prefix), `suf` (suffix), `sub` (substring), `gt` (greater than), `gte` (greater than or equal), `lt` (less than), `lte` (less than or equal). Note: `ex` and `nex` don&#39;t require a `value` field, only `key`.
     * 
     */
    private String op;
    /**
     * @return Request key type to match against
     * 
     */
    private String type;
    /**
     * @return Value to match against. Not required for existence operators (`ex`, `nex`). Use `values` instead for `inc` and `ninc` operators.
     * 
     */
    private @Nullable String value;
    /**
     * @return Values to match against if op is inc, ninc
     * 
     */
    private @Nullable List<String> values;

    private FirewallConfigRulesRuleConditionGroupCondition() {}
    /**
     * @return Key within type to match against
     * 
     */
    public Optional<String> key() {
        return Optional.ofNullable(this.key);
    }
    /**
     * @return Negate the condition. Defaults to false.
     * 
     */
    public Optional<Boolean> neg() {
        return Optional.ofNullable(this.neg);
    }
    /**
     * @return Operator to use for comparison. Options: `re` (regex), `eq` (equals), `neq` (not equals), `ex` (exists), `nex` (not exists), `inc` (includes), `ninc` (not includes), `pre` (prefix), `suf` (suffix), `sub` (substring), `gt` (greater than), `gte` (greater than or equal), `lt` (less than), `lte` (less than or equal). Note: `ex` and `nex` don&#39;t require a `value` field, only `key`.
     * 
     */
    public String op() {
        return this.op;
    }
    /**
     * @return Request key type to match against
     * 
     */
    public String type() {
        return this.type;
    }
    /**
     * @return Value to match against. Not required for existence operators (`ex`, `nex`). Use `values` instead for `inc` and `ninc` operators.
     * 
     */
    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }
    /**
     * @return Values to match against if op is inc, ninc
     * 
     */
    public List<String> values() {
        return this.values == null ? List.of() : this.values;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FirewallConfigRulesRuleConditionGroupCondition defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String key;
        private @Nullable Boolean neg;
        private String op;
        private String type;
        private @Nullable String value;
        private @Nullable List<String> values;
        public Builder() {}
        public Builder(FirewallConfigRulesRuleConditionGroupCondition defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.key = defaults.key;
    	      this.neg = defaults.neg;
    	      this.op = defaults.op;
    	      this.type = defaults.type;
    	      this.value = defaults.value;
    	      this.values = defaults.values;
        }

        @CustomType.Setter
        public Builder key(@Nullable String key) {

            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder neg(@Nullable Boolean neg) {

            this.neg = neg;
            return this;
        }
        @CustomType.Setter
        public Builder op(String op) {
            if (op == null) {
              throw new MissingRequiredPropertyException("FirewallConfigRulesRuleConditionGroupCondition", "op");
            }
            this.op = op;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("FirewallConfigRulesRuleConditionGroupCondition", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder value(@Nullable String value) {

            this.value = value;
            return this;
        }
        @CustomType.Setter
        public Builder values(@Nullable List<String> values) {

            this.values = values;
            return this;
        }
        public Builder values(String... values) {
            return values(List.of(values));
        }
        public FirewallConfigRulesRuleConditionGroupCondition build() {
            final var _resultValue = new FirewallConfigRulesRuleConditionGroupCondition();
            _resultValue.key = key;
            _resultValue.neg = neg;
            _resultValue.op = op;
            _resultValue.type = type;
            _resultValue.value = value;
            _resultValue.values = values;
            return _resultValue;
        }
    }
}
