// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAccessGroupProjectResult {
    /**
     * @return The Access Group ID.
     * 
     */
    private String accessGroupId;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The Project ID.
     * 
     */
    private String projectId;
    /**
     * @return The Access Group Project Role.
     * 
     */
    private String role;
    /**
     * @return The ID of the team the Access Group Project should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    private String teamId;

    private GetAccessGroupProjectResult() {}
    /**
     * @return The Access Group ID.
     * 
     */
    public String accessGroupId() {
        return this.accessGroupId;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The Project ID.
     * 
     */
    public String projectId() {
        return this.projectId;
    }
    /**
     * @return The Access Group Project Role.
     * 
     */
    public String role() {
        return this.role;
    }
    /**
     * @return The ID of the team the Access Group Project should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public String teamId() {
        return this.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccessGroupProjectResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accessGroupId;
        private String id;
        private String projectId;
        private String role;
        private String teamId;
        public Builder() {}
        public Builder(GetAccessGroupProjectResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessGroupId = defaults.accessGroupId;
    	      this.id = defaults.id;
    	      this.projectId = defaults.projectId;
    	      this.role = defaults.role;
    	      this.teamId = defaults.teamId;
        }

        @CustomType.Setter
        public Builder accessGroupId(String accessGroupId) {
            if (accessGroupId == null) {
              throw new MissingRequiredPropertyException("GetAccessGroupProjectResult", "accessGroupId");
            }
            this.accessGroupId = accessGroupId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetAccessGroupProjectResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(String projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetAccessGroupProjectResult", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("GetAccessGroupProjectResult", "role");
            }
            this.role = role;
            return this;
        }
        @CustomType.Setter
        public Builder teamId(String teamId) {
            if (teamId == null) {
              throw new MissingRequiredPropertyException("GetAccessGroupProjectResult", "teamId");
            }
            this.teamId = teamId;
            return this;
        }
        public GetAccessGroupProjectResult build() {
            final var _resultValue = new GetAccessGroupProjectResult();
            _resultValue.accessGroupId = accessGroupId;
            _resultValue.id = id;
            _resultValue.projectId = projectId;
            _resultValue.role = role;
            _resultValue.teamId = teamId;
            return _resultValue;
        }
    }
}
