// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.vercel.outputs.GetDsyncGroupsList;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetDsyncGroupsResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return A list of DSync groups for the team.
     * 
     */
    private List<GetDsyncGroupsList> lists;
    /**
     * @return A map of Identity Provider group names to their Vercel IDs. This can be used to look up the ID of a group by its name using the lookup function.
     * 
     */
    private Map<String,String> map;
    /**
     * @return The ID of the team the Dsync Groups are associated to. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    private String teamId;

    private GetDsyncGroupsResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return A list of DSync groups for the team.
     * 
     */
    public List<GetDsyncGroupsList> lists() {
        return this.lists;
    }
    /**
     * @return A map of Identity Provider group names to their Vercel IDs. This can be used to look up the ID of a group by its name using the lookup function.
     * 
     */
    public Map<String,String> map() {
        return this.map;
    }
    /**
     * @return The ID of the team the Dsync Groups are associated to. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public String teamId() {
        return this.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDsyncGroupsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private List<GetDsyncGroupsList> lists;
        private Map<String,String> map;
        private String teamId;
        public Builder() {}
        public Builder(GetDsyncGroupsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.lists = defaults.lists;
    	      this.map = defaults.map;
    	      this.teamId = defaults.teamId;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetDsyncGroupsResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lists(List<GetDsyncGroupsList> lists) {
            if (lists == null) {
              throw new MissingRequiredPropertyException("GetDsyncGroupsResult", "lists");
            }
            this.lists = lists;
            return this;
        }
        public Builder lists(GetDsyncGroupsList... lists) {
            return lists(List.of(lists));
        }
        @CustomType.Setter
        public Builder map(Map<String,String> map) {
            if (map == null) {
              throw new MissingRequiredPropertyException("GetDsyncGroupsResult", "map");
            }
            this.map = map;
            return this;
        }
        @CustomType.Setter
        public Builder teamId(String teamId) {
            if (teamId == null) {
              throw new MissingRequiredPropertyException("GetDsyncGroupsResult", "teamId");
            }
            this.teamId = teamId;
            return this;
        }
        public GetDsyncGroupsResult build() {
            final var _resultValue = new GetDsyncGroupsResult();
            _resultValue.id = id;
            _resultValue.lists = lists;
            _resultValue.map = map;
            _resultValue.teamId = teamId;
            return _resultValue;
        }
    }
}
