// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetEdgeConfigItemResult {
    /**
     * @return The ID of the Edge Config that the item should exist under.
     * 
     */
    private String id;
    /**
     * @return The name of the key you want to retrieve within your Edge Config.
     * 
     */
    private String key;
    /**
     * @return The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    private String teamId;
    /**
     * @return The value assigned to the key (only set for string values).
     * 
     */
    private String value;
    /**
     * @return Structured JSON value (object/array/number/bool/null) assigned to the key.
     * 
     */
    private Object valueJson;

    private GetEdgeConfigItemResult() {}
    /**
     * @return The ID of the Edge Config that the item should exist under.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the key you want to retrieve within your Edge Config.
     * 
     */
    public String key() {
        return this.key;
    }
    /**
     * @return The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public String teamId() {
        return this.teamId;
    }
    /**
     * @return The value assigned to the key (only set for string values).
     * 
     */
    public String value() {
        return this.value;
    }
    /**
     * @return Structured JSON value (object/array/number/bool/null) assigned to the key.
     * 
     */
    public Object valueJson() {
        return this.valueJson;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetEdgeConfigItemResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String key;
        private String teamId;
        private String value;
        private Object valueJson;
        public Builder() {}
        public Builder(GetEdgeConfigItemResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.key = defaults.key;
    	      this.teamId = defaults.teamId;
    	      this.value = defaults.value;
    	      this.valueJson = defaults.valueJson;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetEdgeConfigItemResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder key(String key) {
            if (key == null) {
              throw new MissingRequiredPropertyException("GetEdgeConfigItemResult", "key");
            }
            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder teamId(String teamId) {
            if (teamId == null) {
              throw new MissingRequiredPropertyException("GetEdgeConfigItemResult", "teamId");
            }
            this.teamId = teamId;
            return this;
        }
        @CustomType.Setter
        public Builder value(String value) {
            if (value == null) {
              throw new MissingRequiredPropertyException("GetEdgeConfigItemResult", "value");
            }
            this.value = value;
            return this;
        }
        @CustomType.Setter
        public Builder valueJson(Object valueJson) {
            if (valueJson == null) {
              throw new MissingRequiredPropertyException("GetEdgeConfigItemResult", "valueJson");
            }
            this.valueJson = valueJson;
            return this;
        }
        public GetEdgeConfigItemResult build() {
            final var _resultValue = new GetEdgeConfigItemResult();
            _resultValue.id = id;
            _resultValue.key = key;
            _resultValue.teamId = teamId;
            _resultValue.value = value;
            _resultValue.valueJson = valueJson;
            return _resultValue;
        }
    }
}
