// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetEndpointVerificationResult {
    /**
     * @return The ID of this resource.
     * 
     */
    private String id;
    /**
     * @return The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    private String teamId;
    /**
     * @return A verification code that should be set in the `x-vercel-verify` response header for your API. This is used to verify that the endpoint belongs to you.
     * 
     */
    private String verificationCode;

    private GetEndpointVerificationResult() {}
    /**
     * @return The ID of this resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public String teamId() {
        return this.teamId;
    }
    /**
     * @return A verification code that should be set in the `x-vercel-verify` response header for your API. This is used to verify that the endpoint belongs to you.
     * 
     */
    public String verificationCode() {
        return this.verificationCode;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetEndpointVerificationResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String teamId;
        private String verificationCode;
        public Builder() {}
        public Builder(GetEndpointVerificationResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.teamId = defaults.teamId;
    	      this.verificationCode = defaults.verificationCode;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetEndpointVerificationResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder teamId(String teamId) {
            if (teamId == null) {
              throw new MissingRequiredPropertyException("GetEndpointVerificationResult", "teamId");
            }
            this.teamId = teamId;
            return this;
        }
        @CustomType.Setter
        public Builder verificationCode(String verificationCode) {
            if (verificationCode == null) {
              throw new MissingRequiredPropertyException("GetEndpointVerificationResult", "verificationCode");
            }
            this.verificationCode = verificationCode;
            return this;
        }
        public GetEndpointVerificationResult build() {
            final var _resultValue = new GetEndpointVerificationResult();
            _resultValue.id = id;
            _resultValue.teamId = teamId;
            _resultValue.verificationCode = verificationCode;
            return _resultValue;
        }
    }
}
