// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.vercel.outputs.GetFeatureFlagSegmentExclude;
import com.pulumiverse.vercel.outputs.GetFeatureFlagSegmentInclude;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetFeatureFlagSegmentResult {
    /**
     * @return A human-readable description of the segment.
     * 
     */
    private String description;
    /**
     * @return Exact entity attribute values that are always excluded from this segment.
     * 
     */
    private List<GetFeatureFlagSegmentExclude> excludes;
    /**
     * @return An optional dashboard hint for the segment.
     * 
     */
    private String hint;
    /**
     * @return The ID of the segment.
     * 
     */
    private String id;
    /**
     * @return Exact entity attribute values that are always part of this segment.
     * 
     */
    private List<GetFeatureFlagSegmentInclude> includes;
    /**
     * @return The human-readable segment name shown in the Vercel dashboard.
     * 
     */
    private String name;
    /**
     * @return The ID of the Vercel project that owns the segment.
     * 
     */
    private String projectId;
    /**
     * @return The stable segment slug used by the Vercel Flags API.
     * 
     */
    private String slug;
    /**
     * @return The ID of the Vercel team. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    private String teamId;

    private GetFeatureFlagSegmentResult() {}
    /**
     * @return A human-readable description of the segment.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Exact entity attribute values that are always excluded from this segment.
     * 
     */
    public List<GetFeatureFlagSegmentExclude> excludes() {
        return this.excludes;
    }
    /**
     * @return An optional dashboard hint for the segment.
     * 
     */
    public String hint() {
        return this.hint;
    }
    /**
     * @return The ID of the segment.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Exact entity attribute values that are always part of this segment.
     * 
     */
    public List<GetFeatureFlagSegmentInclude> includes() {
        return this.includes;
    }
    /**
     * @return The human-readable segment name shown in the Vercel dashboard.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The ID of the Vercel project that owns the segment.
     * 
     */
    public String projectId() {
        return this.projectId;
    }
    /**
     * @return The stable segment slug used by the Vercel Flags API.
     * 
     */
    public String slug() {
        return this.slug;
    }
    /**
     * @return The ID of the Vercel team. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public String teamId() {
        return this.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetFeatureFlagSegmentResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private List<GetFeatureFlagSegmentExclude> excludes;
        private String hint;
        private String id;
        private List<GetFeatureFlagSegmentInclude> includes;
        private String name;
        private String projectId;
        private String slug;
        private String teamId;
        public Builder() {}
        public Builder(GetFeatureFlagSegmentResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.excludes = defaults.excludes;
    	      this.hint = defaults.hint;
    	      this.id = defaults.id;
    	      this.includes = defaults.includes;
    	      this.name = defaults.name;
    	      this.projectId = defaults.projectId;
    	      this.slug = defaults.slug;
    	      this.teamId = defaults.teamId;
        }

        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder excludes(List<GetFeatureFlagSegmentExclude> excludes) {
            if (excludes == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "excludes");
            }
            this.excludes = excludes;
            return this;
        }
        public Builder excludes(GetFeatureFlagSegmentExclude... excludes) {
            return excludes(List.of(excludes));
        }
        @CustomType.Setter
        public Builder hint(String hint) {
            if (hint == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "hint");
            }
            this.hint = hint;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder includes(List<GetFeatureFlagSegmentInclude> includes) {
            if (includes == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "includes");
            }
            this.includes = includes;
            return this;
        }
        public Builder includes(GetFeatureFlagSegmentInclude... includes) {
            return includes(List.of(includes));
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(String projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        @CustomType.Setter
        public Builder slug(String slug) {
            if (slug == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "slug");
            }
            this.slug = slug;
            return this;
        }
        @CustomType.Setter
        public Builder teamId(String teamId) {
            if (teamId == null) {
              throw new MissingRequiredPropertyException("GetFeatureFlagSegmentResult", "teamId");
            }
            this.teamId = teamId;
            return this;
        }
        public GetFeatureFlagSegmentResult build() {
            final var _resultValue = new GetFeatureFlagSegmentResult();
            _resultValue.description = description;
            _resultValue.excludes = excludes;
            _resultValue.hint = hint;
            _resultValue.id = id;
            _resultValue.includes = includes;
            _resultValue.name = name;
            _resultValue.projectId = projectId;
            _resultValue.slug = slug;
            _resultValue.teamId = teamId;
            return _resultValue;
        }
    }
}
