// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.vercel.outputs.GetTeamConfigRemoteCaching;
import com.pulumiverse.vercel.outputs.GetTeamConfigSaml;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTeamConfigResult {
    /**
     * @return A description of the team.
     * 
     */
    private String description;
    /**
     * @return Hostname that&#39;ll be matched with emails on sign-up to automatically join the Team.
     * 
     */
    private String emailDomain;
    /**
     * @return Preview feedback configuration.
     * 
     */
    private String enablePreviewFeedback;
    /**
     * @return Production feedback configuration.
     * 
     */
    private String enableProductionFeedback;
    /**
     * @return Indicates if ip addresses should be accessible in o11y tooling.
     * 
     */
    private Boolean hideIpAddresses;
    /**
     * @return Indicates if ip addresses should be accessible in log drains.
     * 
     */
    private Boolean hideIpAddressesInLogDrains;
    /**
     * @return The ID of the existing Vercel Team.
     * 
     */
    private String id;
    /**
     * @return A code that can be used to join this team. Only visible to Team owners.
     * 
     */
    private String inviteCode;
    /**
     * @return The name of the team.
     * 
     */
    private String name;
    /**
     * @return The hostname that is used as the preview deployment suffix.
     * 
     */
    private String previewDeploymentSuffix;
    /**
     * @return Configuration for Remote Caching.
     * 
     */
    private GetTeamConfigRemoteCaching remoteCaching;
    /**
     * @return Configuration for SAML authentication.
     * 
     */
    private GetTeamConfigSaml saml;
    /**
     * @return The policy for sensitive environment variables.
     * 
     */
    private String sensitiveEnvironmentVariablePolicy;
    /**
     * @return The slug of the team. Used in the URL of the team&#39;s dashboard.
     * 
     */
    private String slug;

    private GetTeamConfigResult() {}
    /**
     * @return A description of the team.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Hostname that&#39;ll be matched with emails on sign-up to automatically join the Team.
     * 
     */
    public String emailDomain() {
        return this.emailDomain;
    }
    /**
     * @return Preview feedback configuration.
     * 
     */
    public String enablePreviewFeedback() {
        return this.enablePreviewFeedback;
    }
    /**
     * @return Production feedback configuration.
     * 
     */
    public String enableProductionFeedback() {
        return this.enableProductionFeedback;
    }
    /**
     * @return Indicates if ip addresses should be accessible in o11y tooling.
     * 
     */
    public Boolean hideIpAddresses() {
        return this.hideIpAddresses;
    }
    /**
     * @return Indicates if ip addresses should be accessible in log drains.
     * 
     */
    public Boolean hideIpAddressesInLogDrains() {
        return this.hideIpAddressesInLogDrains;
    }
    /**
     * @return The ID of the existing Vercel Team.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return A code that can be used to join this team. Only visible to Team owners.
     * 
     */
    public String inviteCode() {
        return this.inviteCode;
    }
    /**
     * @return The name of the team.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The hostname that is used as the preview deployment suffix.
     * 
     */
    public String previewDeploymentSuffix() {
        return this.previewDeploymentSuffix;
    }
    /**
     * @return Configuration for Remote Caching.
     * 
     */
    public GetTeamConfigRemoteCaching remoteCaching() {
        return this.remoteCaching;
    }
    /**
     * @return Configuration for SAML authentication.
     * 
     */
    public GetTeamConfigSaml saml() {
        return this.saml;
    }
    /**
     * @return The policy for sensitive environment variables.
     * 
     */
    public String sensitiveEnvironmentVariablePolicy() {
        return this.sensitiveEnvironmentVariablePolicy;
    }
    /**
     * @return The slug of the team. Used in the URL of the team&#39;s dashboard.
     * 
     */
    public String slug() {
        return this.slug;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTeamConfigResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String emailDomain;
        private String enablePreviewFeedback;
        private String enableProductionFeedback;
        private Boolean hideIpAddresses;
        private Boolean hideIpAddressesInLogDrains;
        private String id;
        private String inviteCode;
        private String name;
        private String previewDeploymentSuffix;
        private GetTeamConfigRemoteCaching remoteCaching;
        private GetTeamConfigSaml saml;
        private String sensitiveEnvironmentVariablePolicy;
        private String slug;
        public Builder() {}
        public Builder(GetTeamConfigResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.emailDomain = defaults.emailDomain;
    	      this.enablePreviewFeedback = defaults.enablePreviewFeedback;
    	      this.enableProductionFeedback = defaults.enableProductionFeedback;
    	      this.hideIpAddresses = defaults.hideIpAddresses;
    	      this.hideIpAddressesInLogDrains = defaults.hideIpAddressesInLogDrains;
    	      this.id = defaults.id;
    	      this.inviteCode = defaults.inviteCode;
    	      this.name = defaults.name;
    	      this.previewDeploymentSuffix = defaults.previewDeploymentSuffix;
    	      this.remoteCaching = defaults.remoteCaching;
    	      this.saml = defaults.saml;
    	      this.sensitiveEnvironmentVariablePolicy = defaults.sensitiveEnvironmentVariablePolicy;
    	      this.slug = defaults.slug;
        }

        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder emailDomain(String emailDomain) {
            if (emailDomain == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "emailDomain");
            }
            this.emailDomain = emailDomain;
            return this;
        }
        @CustomType.Setter
        public Builder enablePreviewFeedback(String enablePreviewFeedback) {
            if (enablePreviewFeedback == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "enablePreviewFeedback");
            }
            this.enablePreviewFeedback = enablePreviewFeedback;
            return this;
        }
        @CustomType.Setter
        public Builder enableProductionFeedback(String enableProductionFeedback) {
            if (enableProductionFeedback == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "enableProductionFeedback");
            }
            this.enableProductionFeedback = enableProductionFeedback;
            return this;
        }
        @CustomType.Setter
        public Builder hideIpAddresses(Boolean hideIpAddresses) {
            if (hideIpAddresses == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "hideIpAddresses");
            }
            this.hideIpAddresses = hideIpAddresses;
            return this;
        }
        @CustomType.Setter
        public Builder hideIpAddressesInLogDrains(Boolean hideIpAddressesInLogDrains) {
            if (hideIpAddressesInLogDrains == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "hideIpAddressesInLogDrains");
            }
            this.hideIpAddressesInLogDrains = hideIpAddressesInLogDrains;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder inviteCode(String inviteCode) {
            if (inviteCode == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "inviteCode");
            }
            this.inviteCode = inviteCode;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder previewDeploymentSuffix(String previewDeploymentSuffix) {
            if (previewDeploymentSuffix == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "previewDeploymentSuffix");
            }
            this.previewDeploymentSuffix = previewDeploymentSuffix;
            return this;
        }
        @CustomType.Setter
        public Builder remoteCaching(GetTeamConfigRemoteCaching remoteCaching) {
            if (remoteCaching == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "remoteCaching");
            }
            this.remoteCaching = remoteCaching;
            return this;
        }
        @CustomType.Setter
        public Builder saml(GetTeamConfigSaml saml) {
            if (saml == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "saml");
            }
            this.saml = saml;
            return this;
        }
        @CustomType.Setter
        public Builder sensitiveEnvironmentVariablePolicy(String sensitiveEnvironmentVariablePolicy) {
            if (sensitiveEnvironmentVariablePolicy == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "sensitiveEnvironmentVariablePolicy");
            }
            this.sensitiveEnvironmentVariablePolicy = sensitiveEnvironmentVariablePolicy;
            return this;
        }
        @CustomType.Setter
        public Builder slug(String slug) {
            if (slug == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigResult", "slug");
            }
            this.slug = slug;
            return this;
        }
        public GetTeamConfigResult build() {
            final var _resultValue = new GetTeamConfigResult();
            _resultValue.description = description;
            _resultValue.emailDomain = emailDomain;
            _resultValue.enablePreviewFeedback = enablePreviewFeedback;
            _resultValue.enableProductionFeedback = enableProductionFeedback;
            _resultValue.hideIpAddresses = hideIpAddresses;
            _resultValue.hideIpAddressesInLogDrains = hideIpAddressesInLogDrains;
            _resultValue.id = id;
            _resultValue.inviteCode = inviteCode;
            _resultValue.name = name;
            _resultValue.previewDeploymentSuffix = previewDeploymentSuffix;
            _resultValue.remoteCaching = remoteCaching;
            _resultValue.saml = saml;
            _resultValue.sensitiveEnvironmentVariablePolicy = sensitiveEnvironmentVariablePolicy;
            _resultValue.slug = slug;
            return _resultValue;
        }
    }
}
