// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.vercel.outputs.GetTeamConfigSamlRoles;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetTeamConfigSaml {
    /**
     * @return Indicates if SAML is enforced for the team.
     * 
     */
    private Boolean enforced;
    /**
     * @return Directory groups to role or access group mappings. For each directory group, either a role or access group id is specified.
     * 
     */
    private Map<String,GetTeamConfigSamlRoles> roles;

    private GetTeamConfigSaml() {}
    /**
     * @return Indicates if SAML is enforced for the team.
     * 
     */
    public Boolean enforced() {
        return this.enforced;
    }
    /**
     * @return Directory groups to role or access group mappings. For each directory group, either a role or access group id is specified.
     * 
     */
    public Map<String,GetTeamConfigSamlRoles> roles() {
        return this.roles;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTeamConfigSaml defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean enforced;
        private Map<String,GetTeamConfigSamlRoles> roles;
        public Builder() {}
        public Builder(GetTeamConfigSaml defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enforced = defaults.enforced;
    	      this.roles = defaults.roles;
        }

        @CustomType.Setter
        public Builder enforced(Boolean enforced) {
            if (enforced == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigSaml", "enforced");
            }
            this.enforced = enforced;
            return this;
        }
        @CustomType.Setter
        public Builder roles(Map<String,GetTeamConfigSamlRoles> roles) {
            if (roles == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigSaml", "roles");
            }
            this.roles = roles;
            return this;
        }
        public GetTeamConfigSaml build() {
            final var _resultValue = new GetTeamConfigSaml();
            _resultValue.enforced = enforced;
            _resultValue.roles = roles;
            return _resultValue;
        }
    }
}
