// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTraceDrainSamplingRule {
    /**
     * @return Environment this sampling rule applies to.
     * 
     */
    private String environment;
    /**
     * @return Sampling rate from 0 to 1.
     * 
     */
    private Double rate;
    /**
     * @return Request path prefix this sampling rule applies to.
     * 
     */
    private String requestPath;

    private GetTraceDrainSamplingRule() {}
    /**
     * @return Environment this sampling rule applies to.
     * 
     */
    public String environment() {
        return this.environment;
    }
    /**
     * @return Sampling rate from 0 to 1.
     * 
     */
    public Double rate() {
        return this.rate;
    }
    /**
     * @return Request path prefix this sampling rule applies to.
     * 
     */
    public String requestPath() {
        return this.requestPath;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTraceDrainSamplingRule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String environment;
        private Double rate;
        private String requestPath;
        public Builder() {}
        public Builder(GetTraceDrainSamplingRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.environment = defaults.environment;
    	      this.rate = defaults.rate;
    	      this.requestPath = defaults.requestPath;
        }

        @CustomType.Setter
        public Builder environment(String environment) {
            if (environment == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainSamplingRule", "environment");
            }
            this.environment = environment;
            return this;
        }
        @CustomType.Setter
        public Builder rate(Double rate) {
            if (rate == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainSamplingRule", "rate");
            }
            this.rate = rate;
            return this;
        }
        @CustomType.Setter
        public Builder requestPath(String requestPath) {
            if (requestPath == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainSamplingRule", "requestPath");
            }
            this.requestPath = requestPath;
            return this;
        }
        public GetTraceDrainSamplingRule build() {
            final var _resultValue = new GetTraceDrainSamplingRule();
            _resultValue.environment = environment;
            _resultValue.rate = rate;
            _resultValue.requestPath = requestPath;
            return _resultValue;
        }
    }
}
