// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.vercel.outputs.GetTraceDrainSamplingRule;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetTraceDrainResult {
    /**
     * @return The OTLP/HTTP format trace data is delivered in. Can be `json` or `proto`.
     * 
     */
    private String deliveryFormat;
    /**
     * @return The OTLP/HTTP traces endpoint.
     * 
     */
    private String endpoint;
    /**
     * @return Custom headers included in requests to the trace drain endpoint.
     * 
     */
    private Map<String,String> headers;
    /**
     * @return The ID of the Trace Drain.
     * 
     */
    private String id;
    /**
     * @return The human-readable name of the Trace Drain.
     * 
     */
    private String name;
    /**
     * @return A list of project IDs that the trace drain is associated with. If omitted, traces are sent for all projects.
     * 
     */
    private List<String> projectIds;
    /**
     * @return Ordered sampling rules for traces sent to this drain.
     * 
     */
    private List<GetTraceDrainSamplingRule> samplingRules;
    /**
     * @return The ID of the team the Trace Drain exists under. Required when reading a team resource if a default team has not been set in the provider.
     * 
     */
    private String teamId;

    private GetTraceDrainResult() {}
    /**
     * @return The OTLP/HTTP format trace data is delivered in. Can be `json` or `proto`.
     * 
     */
    public String deliveryFormat() {
        return this.deliveryFormat;
    }
    /**
     * @return The OTLP/HTTP traces endpoint.
     * 
     */
    public String endpoint() {
        return this.endpoint;
    }
    /**
     * @return Custom headers included in requests to the trace drain endpoint.
     * 
     */
    public Map<String,String> headers() {
        return this.headers;
    }
    /**
     * @return The ID of the Trace Drain.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The human-readable name of the Trace Drain.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return A list of project IDs that the trace drain is associated with. If omitted, traces are sent for all projects.
     * 
     */
    public List<String> projectIds() {
        return this.projectIds;
    }
    /**
     * @return Ordered sampling rules for traces sent to this drain.
     * 
     */
    public List<GetTraceDrainSamplingRule> samplingRules() {
        return this.samplingRules;
    }
    /**
     * @return The ID of the team the Trace Drain exists under. Required when reading a team resource if a default team has not been set in the provider.
     * 
     */
    public String teamId() {
        return this.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTraceDrainResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String deliveryFormat;
        private String endpoint;
        private Map<String,String> headers;
        private String id;
        private String name;
        private List<String> projectIds;
        private List<GetTraceDrainSamplingRule> samplingRules;
        private String teamId;
        public Builder() {}
        public Builder(GetTraceDrainResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.deliveryFormat = defaults.deliveryFormat;
    	      this.endpoint = defaults.endpoint;
    	      this.headers = defaults.headers;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.projectIds = defaults.projectIds;
    	      this.samplingRules = defaults.samplingRules;
    	      this.teamId = defaults.teamId;
        }

        @CustomType.Setter
        public Builder deliveryFormat(String deliveryFormat) {
            if (deliveryFormat == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainResult", "deliveryFormat");
            }
            this.deliveryFormat = deliveryFormat;
            return this;
        }
        @CustomType.Setter
        public Builder endpoint(String endpoint) {
            if (endpoint == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainResult", "endpoint");
            }
            this.endpoint = endpoint;
            return this;
        }
        @CustomType.Setter
        public Builder headers(Map<String,String> headers) {
            if (headers == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainResult", "headers");
            }
            this.headers = headers;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder projectIds(List<String> projectIds) {
            if (projectIds == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainResult", "projectIds");
            }
            this.projectIds = projectIds;
            return this;
        }
        public Builder projectIds(String... projectIds) {
            return projectIds(List.of(projectIds));
        }
        @CustomType.Setter
        public Builder samplingRules(List<GetTraceDrainSamplingRule> samplingRules) {
            if (samplingRules == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainResult", "samplingRules");
            }
            this.samplingRules = samplingRules;
            return this;
        }
        public Builder samplingRules(GetTraceDrainSamplingRule... samplingRules) {
            return samplingRules(List.of(samplingRules));
        }
        @CustomType.Setter
        public Builder teamId(String teamId) {
            if (teamId == null) {
              throw new MissingRequiredPropertyException("GetTraceDrainResult", "teamId");
            }
            this.teamId = teamId;
            return this;
        }
        public GetTraceDrainResult build() {
            final var _resultValue = new GetTraceDrainResult();
            _resultValue.deliveryFormat = deliveryFormat;
            _resultValue.endpoint = endpoint;
            _resultValue.headers = headers;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.projectIds = projectIds;
            _resultValue.samplingRules = samplingRules;
            _resultValue.teamId = teamId;
            return _resultValue;
        }
    }
}
