// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTeamConfigDefaultDeploymentProtectionVercelAuthentication {
    /**
     * @return The default protection level, or none when disabled.
     * 
     */
    private String deploymentType;

    private GetTeamConfigDefaultDeploymentProtectionVercelAuthentication() {}
    /**
     * @return The default protection level, or none when disabled.
     * 
     */
    public String deploymentType() {
        return this.deploymentType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTeamConfigDefaultDeploymentProtectionVercelAuthentication defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String deploymentType;
        public Builder() {}
        public Builder(GetTeamConfigDefaultDeploymentProtectionVercelAuthentication defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.deploymentType = defaults.deploymentType;
        }

        @CustomType.Setter
        public Builder deploymentType(String deploymentType) {
            if (deploymentType == null) {
              throw new MissingRequiredPropertyException("GetTeamConfigDefaultDeploymentProtectionVercelAuthentication", "deploymentType");
            }
            this.deploymentType = deploymentType;
            return this;
        }
        public GetTeamConfigDefaultDeploymentProtectionVercelAuthentication build() {
            final var _resultValue = new GetTeamConfigDefaultDeploymentProtectionVercelAuthentication();
            _resultValue.deploymentType = deploymentType;
            return _resultValue;
        }
    }
}
