// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.vercel.outputs.ProjectTrustedSourcesProjectCustomAllowFrom;
import com.pulumiverse.vercel.outputs.ProjectTrustedSourcesProjectCustomAllowTo;
import java.util.Objects;

@CustomType
public final class ProjectTrustedSourcesProjectCustomAllow {
    /**
     * @return The source environments on the trusted project that are allowed to access the target environments.
     * 
     */
    private ProjectTrustedSourcesProjectCustomAllowFrom from;
    /**
     * @return The target environments on this project that may be accessed.
     * 
     */
    private ProjectTrustedSourcesProjectCustomAllowTo to;

    private ProjectTrustedSourcesProjectCustomAllow() {}
    /**
     * @return The source environments on the trusted project that are allowed to access the target environments.
     * 
     */
    public ProjectTrustedSourcesProjectCustomAllowFrom from() {
        return this.from;
    }
    /**
     * @return The target environments on this project that may be accessed.
     * 
     */
    public ProjectTrustedSourcesProjectCustomAllowTo to() {
        return this.to;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ProjectTrustedSourcesProjectCustomAllow defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private ProjectTrustedSourcesProjectCustomAllowFrom from;
        private ProjectTrustedSourcesProjectCustomAllowTo to;
        public Builder() {}
        public Builder(ProjectTrustedSourcesProjectCustomAllow defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.from = defaults.from;
    	      this.to = defaults.to;
        }

        @CustomType.Setter
        public Builder from(ProjectTrustedSourcesProjectCustomAllowFrom from) {
            if (from == null) {
              throw new MissingRequiredPropertyException("ProjectTrustedSourcesProjectCustomAllow", "from");
            }
            this.from = from;
            return this;
        }
        @CustomType.Setter
        public Builder to(ProjectTrustedSourcesProjectCustomAllowTo to) {
            if (to == null) {
              throw new MissingRequiredPropertyException("ProjectTrustedSourcesProjectCustomAllow", "to");
            }
            this.to = to;
            return this;
        }
        public ProjectTrustedSourcesProjectCustomAllow build() {
            final var _resultValue = new ProjectTrustedSourcesProjectCustomAllow();
            _resultValue.from = from;
            _resultValue.to = to;
            return _resultValue;
        }
    }
}
