// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel.Outputs
{

    [OutputType]
    public sealed class GetProjectRollingReleaseStageResult
    {
        /// <summary>
        /// The duration in minutes to wait before advancing to the next stage. Present for automatic advancement type.
        /// </summary>
        public readonly int Duration;
        /// <summary>
        /// The percentage of traffic to route to this stage.
        /// </summary>
        public readonly int TargetPercentage;

        [OutputConstructor]
        private GetProjectRollingReleaseStageResult(
            int duration,

            int targetPercentage)
        {
            Duration = duration;
            TargetPercentage = targetPercentage;
        }
    }
}
