// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel.Outputs
{

    [OutputType]
    public sealed class GetProjectOidcTokenConfigResult
    {
        /// <summary>
        /// When true, Vercel issued OpenID Connect (OIDC) tokens will be available on the compute environments. See https://vercel.com/docs/security/secure-backend-access/oidc for more information.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Configures the URL of the `iss` claim. `team` = `https://oidc.vercel.com/[team_slug]` `global` = `https://oidc.vercel.com`
        /// </summary>
        public readonly string IssuerMode;

        [OutputConstructor]
        private GetProjectOidcTokenConfigResult(
            bool enabled,

            string issuerMode)
        {
            Enabled = enabled;
            IssuerMode = issuerMode;
        }
    }
}
