// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel.Outputs
{

    [OutputType]
    public sealed class ProjectRouteRoute
    {
        /// <summary>
        /// Whether the `Src` matcher is case-sensitive.
        /// </summary>
        public readonly bool? CaseSensitive;
        /// <summary>
        /// The destination for rewrites or redirects.
        /// </summary>
        public readonly string? Dest;
        /// <summary>
        /// Conditions that must be present for the rule to match.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectRouteRouteHa> Has;
        /// <summary>
        /// Headers to set for the matched request.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Headers;
        /// <summary>
        /// Conditions that must be absent for the rule to match.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectRouteRouteMissing> Missings;
        /// <summary>
        /// Whether the rule should respect cache control headers from the origin.
        /// </summary>
        public readonly bool? RespectOriginCacheControl;
        /// <summary>
        /// The source pattern to match.
        /// </summary>
        public readonly string Src;
        /// <summary>
        /// The HTTP status code to set for redirects or status-only rules.
        /// </summary>
        public readonly int? Status;
        /// <summary>
        /// Transforms applied to the request or response when the rule matches.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectRouteRouteTransform> Transforms;

        [OutputConstructor]
        private ProjectRouteRoute(
            bool? caseSensitive,

            string? dest,

            ImmutableArray<Outputs.ProjectRouteRouteHa> has,

            ImmutableDictionary<string, string>? headers,

            ImmutableArray<Outputs.ProjectRouteRouteMissing> missings,

            bool? respectOriginCacheControl,

            string src,

            int? status,

            ImmutableArray<Outputs.ProjectRouteRouteTransform> transforms)
        {
            CaseSensitive = caseSensitive;
            Dest = dest;
            Has = has;
            Headers = headers;
            Missings = missings;
            RespectOriginCacheControl = respectOriginCacheControl;
            Src = src;
            Status = status;
            Transforms = transforms;
        }
    }
}
