// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel.Outputs
{

    [OutputType]
    public sealed class ProjectPasswordProtection
    {
        /// <summary>
        /// The deployment environment to protect. Must be one of `standard_protection`, `all_deployments`, or `only_preview_deployments`.
        /// </summary>
        public readonly string DeploymentType;
        /// <summary>
        /// The password that visitors must enter to gain access to your Preview Deployments. Drift detection is not possible for this field.
        /// </summary>
        public readonly string Password;

        [OutputConstructor]
        private ProjectPasswordProtection(
            string deploymentType,

            string password)
        {
            DeploymentType = deploymentType;
            Password = password;
        }
    }
}
