// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vercel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-vercel/sdk/v5/go/vercel/internal"
)

// Provides metadata about an existing object in a Vercel Blob store.
func LookupBlobObject(ctx *pulumi.Context, args *LookupBlobObjectArgs, opts ...pulumi.InvokeOption) (*LookupBlobObjectResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupBlobObjectResult
	err := ctx.Invoke("vercel:index/getBlobObject:getBlobObject", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBlobObject.
type LookupBlobObjectArgs struct {
	// The pathname of the Blob object within the store.
	Pathname string `pulumi:"pathname"`
	// The ID of the Blob store that contains the object.
	StoreId string `pulumi:"storeId"`
	// The ID of the team that owns the Blob store. Required when configuring a team resource if a default team has not been set in the provider.
	TeamId *string `pulumi:"teamId"`
}

// A collection of values returned by getBlobObject.
type LookupBlobObjectResult struct {
	// The full Cache-Control header stored on the Blob object.
	CacheControl string `pulumi:"cacheControl"`
	// The cache max-age, in seconds, stored on the Blob object.
	CacheControlMaxAge int `pulumi:"cacheControlMaxAge"`
	// The content disposition returned for the Blob object.
	ContentDisposition string `pulumi:"contentDisposition"`
	// The content type stored on the Blob object.
	ContentType string `pulumi:"contentType"`
	// The Blob object URL with download semantics enabled.
	DownloadUrl string `pulumi:"downloadUrl"`
	// The current ETag for the Blob object.
	Etag string `pulumi:"etag"`
	// The unique identifier for this Blob object. Format: `store_id/pathname`.
	Id string `pulumi:"id"`
	// The pathname of the Blob object within the store.
	Pathname string `pulumi:"pathname"`
	// The size of the Blob object in bytes.
	Size int `pulumi:"size"`
	// The ID of the Blob store that contains the object.
	StoreId string `pulumi:"storeId"`
	// The ID of the team that owns the Blob store. Required when configuring a team resource if a default team has not been set in the provider.
	TeamId string `pulumi:"teamId"`
	// The timestamp at which the Blob object was uploaded.
	UploadedAt string `pulumi:"uploadedAt"`
	// The canonical URL for the Blob object.
	Url string `pulumi:"url"`
}

func LookupBlobObjectOutput(ctx *pulumi.Context, args LookupBlobObjectOutputArgs, opts ...pulumi.InvokeOption) LookupBlobObjectResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupBlobObjectResultOutput, error) {
			args := v.(LookupBlobObjectArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("vercel:index/getBlobObject:getBlobObject", args, LookupBlobObjectResultOutput{}, options).(LookupBlobObjectResultOutput), nil
		}).(LookupBlobObjectResultOutput)
}

// A collection of arguments for invoking getBlobObject.
type LookupBlobObjectOutputArgs struct {
	// The pathname of the Blob object within the store.
	Pathname pulumi.StringInput `pulumi:"pathname"`
	// The ID of the Blob store that contains the object.
	StoreId pulumi.StringInput `pulumi:"storeId"`
	// The ID of the team that owns the Blob store. Required when configuring a team resource if a default team has not been set in the provider.
	TeamId pulumi.StringPtrInput `pulumi:"teamId"`
}

func (LookupBlobObjectOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBlobObjectArgs)(nil)).Elem()
}

// A collection of values returned by getBlobObject.
type LookupBlobObjectResultOutput struct{ *pulumi.OutputState }

func (LookupBlobObjectResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBlobObjectResult)(nil)).Elem()
}

func (o LookupBlobObjectResultOutput) ToLookupBlobObjectResultOutput() LookupBlobObjectResultOutput {
	return o
}

func (o LookupBlobObjectResultOutput) ToLookupBlobObjectResultOutputWithContext(ctx context.Context) LookupBlobObjectResultOutput {
	return o
}

// The full Cache-Control header stored on the Blob object.
func (o LookupBlobObjectResultOutput) CacheControl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.CacheControl }).(pulumi.StringOutput)
}

// The cache max-age, in seconds, stored on the Blob object.
func (o LookupBlobObjectResultOutput) CacheControlMaxAge() pulumi.IntOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) int { return v.CacheControlMaxAge }).(pulumi.IntOutput)
}

// The content disposition returned for the Blob object.
func (o LookupBlobObjectResultOutput) ContentDisposition() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.ContentDisposition }).(pulumi.StringOutput)
}

// The content type stored on the Blob object.
func (o LookupBlobObjectResultOutput) ContentType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.ContentType }).(pulumi.StringOutput)
}

// The Blob object URL with download semantics enabled.
func (o LookupBlobObjectResultOutput) DownloadUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.DownloadUrl }).(pulumi.StringOutput)
}

// The current ETag for the Blob object.
func (o LookupBlobObjectResultOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.Etag }).(pulumi.StringOutput)
}

// The unique identifier for this Blob object. Format: `store_id/pathname`.
func (o LookupBlobObjectResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.Id }).(pulumi.StringOutput)
}

// The pathname of the Blob object within the store.
func (o LookupBlobObjectResultOutput) Pathname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.Pathname }).(pulumi.StringOutput)
}

// The size of the Blob object in bytes.
func (o LookupBlobObjectResultOutput) Size() pulumi.IntOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) int { return v.Size }).(pulumi.IntOutput)
}

// The ID of the Blob store that contains the object.
func (o LookupBlobObjectResultOutput) StoreId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.StoreId }).(pulumi.StringOutput)
}

// The ID of the team that owns the Blob store. Required when configuring a team resource if a default team has not been set in the provider.
func (o LookupBlobObjectResultOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.TeamId }).(pulumi.StringOutput)
}

// The timestamp at which the Blob object was uploaded.
func (o LookupBlobObjectResultOutput) UploadedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.UploadedAt }).(pulumi.StringOutput)
}

// The canonical URL for the Blob object.
func (o LookupBlobObjectResultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBlobObjectResult) string { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupBlobObjectResultOutput{})
}
