// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vercel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-vercel/sdk/go/vercel/internal"
)

func LookupCustomEnvironment(ctx *pulumi.Context, args *LookupCustomEnvironmentArgs, opts ...pulumi.InvokeOption) (*LookupCustomEnvironmentResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCustomEnvironmentResult
	err := ctx.Invoke("vercel:index/getCustomEnvironment:getCustomEnvironment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCustomEnvironment.
type LookupCustomEnvironmentArgs struct {
	Name      string  `pulumi:"name"`
	ProjectId string  `pulumi:"projectId"`
	TeamId    *string `pulumi:"teamId"`
}

// A collection of values returned by getCustomEnvironment.
type LookupCustomEnvironmentResult struct {
	BranchTracking GetCustomEnvironmentBranchTracking `pulumi:"branchTracking"`
	Description    string                             `pulumi:"description"`
	Id             string                             `pulumi:"id"`
	Name           string                             `pulumi:"name"`
	ProjectId      string                             `pulumi:"projectId"`
	TeamId         string                             `pulumi:"teamId"`
}

func LookupCustomEnvironmentOutput(ctx *pulumi.Context, args LookupCustomEnvironmentOutputArgs, opts ...pulumi.InvokeOption) LookupCustomEnvironmentResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCustomEnvironmentResultOutput, error) {
			args := v.(LookupCustomEnvironmentArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupCustomEnvironmentResult
			secret, err := ctx.InvokePackageRaw("vercel:index/getCustomEnvironment:getCustomEnvironment", args, &rv, "", opts...)
			if err != nil {
				return LookupCustomEnvironmentResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupCustomEnvironmentResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupCustomEnvironmentResultOutput), nil
			}
			return output, nil
		}).(LookupCustomEnvironmentResultOutput)
}

// A collection of arguments for invoking getCustomEnvironment.
type LookupCustomEnvironmentOutputArgs struct {
	Name      pulumi.StringInput    `pulumi:"name"`
	ProjectId pulumi.StringInput    `pulumi:"projectId"`
	TeamId    pulumi.StringPtrInput `pulumi:"teamId"`
}

func (LookupCustomEnvironmentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCustomEnvironmentArgs)(nil)).Elem()
}

// A collection of values returned by getCustomEnvironment.
type LookupCustomEnvironmentResultOutput struct{ *pulumi.OutputState }

func (LookupCustomEnvironmentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCustomEnvironmentResult)(nil)).Elem()
}

func (o LookupCustomEnvironmentResultOutput) ToLookupCustomEnvironmentResultOutput() LookupCustomEnvironmentResultOutput {
	return o
}

func (o LookupCustomEnvironmentResultOutput) ToLookupCustomEnvironmentResultOutputWithContext(ctx context.Context) LookupCustomEnvironmentResultOutput {
	return o
}

func (o LookupCustomEnvironmentResultOutput) BranchTracking() GetCustomEnvironmentBranchTrackingOutput {
	return o.ApplyT(func(v LookupCustomEnvironmentResult) GetCustomEnvironmentBranchTracking { return v.BranchTracking }).(GetCustomEnvironmentBranchTrackingOutput)
}

func (o LookupCustomEnvironmentResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCustomEnvironmentResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupCustomEnvironmentResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCustomEnvironmentResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCustomEnvironmentResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCustomEnvironmentResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupCustomEnvironmentResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCustomEnvironmentResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

func (o LookupCustomEnvironmentResultOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCustomEnvironmentResult) string { return v.TeamId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCustomEnvironmentResultOutput{})
}
