// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vercel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-vercel/sdk/v4/go/vercel/internal"
)

// Provides a Network resource.
type Network struct {
	pulumi.CustomResourceState

	// The ID of the AWS Account in which the network exists.
	AwsAccountId pulumi.StringOutput `pulumi:"awsAccountId"`
	// The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
	AwsAvailabilityZoneIds pulumi.StringArrayOutput `pulumi:"awsAvailabilityZoneIds"`
	// The AWS Region in which the network exists.
	AwsRegion pulumi.StringOutput `pulumi:"awsRegion"`
	// The CIDR range of the Network.
	Cidr pulumi.StringOutput `pulumi:"cidr"`
	// The egress IP addresses of the Network.
	EgressIpAddresses pulumi.StringArrayOutput `pulumi:"egressIpAddresses"`
	// The name of the network.
	Name pulumi.StringOutput `pulumi:"name"`
	// The Vercel region in which the Network exists.
	Region pulumi.StringOutput `pulumi:"region"`
	// The status of the Network.
	Status pulumi.StringOutput `pulumi:"status"`
	// The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
	TeamId   pulumi.StringOutput      `pulumi:"teamId"`
	Timeouts NetworkTimeoutsPtrOutput `pulumi:"timeouts"`
	// The ID of the AWS VPC which hosts the network.
	VpcId pulumi.StringOutput `pulumi:"vpcId"`
}

// NewNetwork registers a new resource with the given unique name, arguments, and options.
func NewNetwork(ctx *pulumi.Context,
	name string, args *NetworkArgs, opts ...pulumi.ResourceOption) (*Network, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Cidr == nil {
		return nil, errors.New("invalid value for required argument 'Cidr'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Network
	err := ctx.RegisterResource("vercel:index/network:Network", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetwork gets an existing Network resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetwork(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkState, opts ...pulumi.ResourceOption) (*Network, error) {
	var resource Network
	err := ctx.ReadResource("vercel:index/network:Network", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Network resources.
type networkState struct {
	// The ID of the AWS Account in which the network exists.
	AwsAccountId *string `pulumi:"awsAccountId"`
	// The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
	AwsAvailabilityZoneIds []string `pulumi:"awsAvailabilityZoneIds"`
	// The AWS Region in which the network exists.
	AwsRegion *string `pulumi:"awsRegion"`
	// The CIDR range of the Network.
	Cidr *string `pulumi:"cidr"`
	// The egress IP addresses of the Network.
	EgressIpAddresses []string `pulumi:"egressIpAddresses"`
	// The name of the network.
	Name *string `pulumi:"name"`
	// The Vercel region in which the Network exists.
	Region *string `pulumi:"region"`
	// The status of the Network.
	Status *string `pulumi:"status"`
	// The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
	TeamId   *string          `pulumi:"teamId"`
	Timeouts *NetworkTimeouts `pulumi:"timeouts"`
	// The ID of the AWS VPC which hosts the network.
	VpcId *string `pulumi:"vpcId"`
}

type NetworkState struct {
	// The ID of the AWS Account in which the network exists.
	AwsAccountId pulumi.StringPtrInput
	// The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
	AwsAvailabilityZoneIds pulumi.StringArrayInput
	// The AWS Region in which the network exists.
	AwsRegion pulumi.StringPtrInput
	// The CIDR range of the Network.
	Cidr pulumi.StringPtrInput
	// The egress IP addresses of the Network.
	EgressIpAddresses pulumi.StringArrayInput
	// The name of the network.
	Name pulumi.StringPtrInput
	// The Vercel region in which the Network exists.
	Region pulumi.StringPtrInput
	// The status of the Network.
	Status pulumi.StringPtrInput
	// The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
	TeamId   pulumi.StringPtrInput
	Timeouts NetworkTimeoutsPtrInput
	// The ID of the AWS VPC which hosts the network.
	VpcId pulumi.StringPtrInput
}

func (NetworkState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkState)(nil)).Elem()
}

type networkArgs struct {
	// The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
	AwsAvailabilityZoneIds []string `pulumi:"awsAvailabilityZoneIds"`
	// The CIDR range of the Network.
	Cidr string `pulumi:"cidr"`
	// The name of the network.
	Name *string `pulumi:"name"`
	// The Vercel region in which the Network exists.
	Region string `pulumi:"region"`
	// The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
	TeamId   *string          `pulumi:"teamId"`
	Timeouts *NetworkTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a Network resource.
type NetworkArgs struct {
	// The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
	AwsAvailabilityZoneIds pulumi.StringArrayInput
	// The CIDR range of the Network.
	Cidr pulumi.StringInput
	// The name of the network.
	Name pulumi.StringPtrInput
	// The Vercel region in which the Network exists.
	Region pulumi.StringInput
	// The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
	TeamId   pulumi.StringPtrInput
	Timeouts NetworkTimeoutsPtrInput
}

func (NetworkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkArgs)(nil)).Elem()
}

type NetworkInput interface {
	pulumi.Input

	ToNetworkOutput() NetworkOutput
	ToNetworkOutputWithContext(ctx context.Context) NetworkOutput
}

func (*Network) ElementType() reflect.Type {
	return reflect.TypeOf((**Network)(nil)).Elem()
}

func (i *Network) ToNetworkOutput() NetworkOutput {
	return i.ToNetworkOutputWithContext(context.Background())
}

func (i *Network) ToNetworkOutputWithContext(ctx context.Context) NetworkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkOutput)
}

// NetworkArrayInput is an input type that accepts NetworkArray and NetworkArrayOutput values.
// You can construct a concrete instance of `NetworkArrayInput` via:
//
//	NetworkArray{ NetworkArgs{...} }
type NetworkArrayInput interface {
	pulumi.Input

	ToNetworkArrayOutput() NetworkArrayOutput
	ToNetworkArrayOutputWithContext(context.Context) NetworkArrayOutput
}

type NetworkArray []NetworkInput

func (NetworkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Network)(nil)).Elem()
}

func (i NetworkArray) ToNetworkArrayOutput() NetworkArrayOutput {
	return i.ToNetworkArrayOutputWithContext(context.Background())
}

func (i NetworkArray) ToNetworkArrayOutputWithContext(ctx context.Context) NetworkArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkArrayOutput)
}

// NetworkMapInput is an input type that accepts NetworkMap and NetworkMapOutput values.
// You can construct a concrete instance of `NetworkMapInput` via:
//
//	NetworkMap{ "key": NetworkArgs{...} }
type NetworkMapInput interface {
	pulumi.Input

	ToNetworkMapOutput() NetworkMapOutput
	ToNetworkMapOutputWithContext(context.Context) NetworkMapOutput
}

type NetworkMap map[string]NetworkInput

func (NetworkMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Network)(nil)).Elem()
}

func (i NetworkMap) ToNetworkMapOutput() NetworkMapOutput {
	return i.ToNetworkMapOutputWithContext(context.Background())
}

func (i NetworkMap) ToNetworkMapOutputWithContext(ctx context.Context) NetworkMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkMapOutput)
}

type NetworkOutput struct{ *pulumi.OutputState }

func (NetworkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Network)(nil)).Elem()
}

func (o NetworkOutput) ToNetworkOutput() NetworkOutput {
	return o
}

func (o NetworkOutput) ToNetworkOutputWithContext(ctx context.Context) NetworkOutput {
	return o
}

// The ID of the AWS Account in which the network exists.
func (o NetworkOutput) AwsAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.AwsAccountId }).(pulumi.StringOutput)
}

// The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
func (o NetworkOutput) AwsAvailabilityZoneIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Network) pulumi.StringArrayOutput { return v.AwsAvailabilityZoneIds }).(pulumi.StringArrayOutput)
}

// The AWS Region in which the network exists.
func (o NetworkOutput) AwsRegion() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.AwsRegion }).(pulumi.StringOutput)
}

// The CIDR range of the Network.
func (o NetworkOutput) Cidr() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.Cidr }).(pulumi.StringOutput)
}

// The egress IP addresses of the Network.
func (o NetworkOutput) EgressIpAddresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Network) pulumi.StringArrayOutput { return v.EgressIpAddresses }).(pulumi.StringArrayOutput)
}

// The name of the network.
func (o NetworkOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The Vercel region in which the Network exists.
func (o NetworkOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// The status of the Network.
func (o NetworkOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
func (o NetworkOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.TeamId }).(pulumi.StringOutput)
}

func (o NetworkOutput) Timeouts() NetworkTimeoutsPtrOutput {
	return o.ApplyT(func(v *Network) NetworkTimeoutsPtrOutput { return v.Timeouts }).(NetworkTimeoutsPtrOutput)
}

// The ID of the AWS VPC which hosts the network.
func (o NetworkOutput) VpcId() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.VpcId }).(pulumi.StringOutput)
}

type NetworkArrayOutput struct{ *pulumi.OutputState }

func (NetworkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Network)(nil)).Elem()
}

func (o NetworkArrayOutput) ToNetworkArrayOutput() NetworkArrayOutput {
	return o
}

func (o NetworkArrayOutput) ToNetworkArrayOutputWithContext(ctx context.Context) NetworkArrayOutput {
	return o
}

func (o NetworkArrayOutput) Index(i pulumi.IntInput) NetworkOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Network {
		return vs[0].([]*Network)[vs[1].(int)]
	}).(NetworkOutput)
}

type NetworkMapOutput struct{ *pulumi.OutputState }

func (NetworkMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Network)(nil)).Elem()
}

func (o NetworkMapOutput) ToNetworkMapOutput() NetworkMapOutput {
	return o
}

func (o NetworkMapOutput) ToNetworkMapOutputWithContext(ctx context.Context) NetworkMapOutput {
	return o
}

func (o NetworkMapOutput) MapIndex(k pulumi.StringInput) NetworkOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Network {
		return vs[0].(map[string]*Network)[vs[1].(string)]
	}).(NetworkOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkInput)(nil)).Elem(), &Network{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkArrayInput)(nil)).Elem(), NetworkArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkMapInput)(nil)).Elem(), NetworkMap{})
	pulumi.RegisterOutputType(NetworkOutput{})
	pulumi.RegisterOutputType(NetworkArrayOutput{})
	pulumi.RegisterOutputType(NetworkMapOutput{})
}
