// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AiGatewayApiKeyAiGatewayQuota {
    /**
     * Spend percentages (a subset of `[50, 75, 100]`) at which to send a spend alert.
     */
    alertThresholds?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * The quota limit amount in US dollars.
     */
    limitAmount: pulumi.Input<number>;
    /**
     * How often the quota refreshes. Must be one of `daily`, `weekly`, `monthly` or `none`. Defaults to `none`.
     */
    refreshPeriod?: pulumi.Input<string>;
}

export interface AuditLogDrainHttp {
    /**
     * The compression applied to HTTP request bodies. Can be `gzip` or `none`.
     */
    compression?: pulumi.Input<string>;
    /**
     * The format used to deliver Audit Log events. Can be `json` or `ndjson`.
     */
    encoding: pulumi.Input<string>;
    /**
     * The HTTPS endpoint that receives Audit Log events.
     */
    endpoint: pulumi.Input<string>;
    /**
     * Custom headers included in requests to the HTTP endpoint.
     */
    headers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * A custom secret used to sign Audit Log events. If omitted, Vercel generates one.
     */
    secret?: pulumi.Input<string>;
}

export interface AuditLogDrainS3 {
    /**
     * The format used to write Audit Log events. Can be `json` or `ndjson`.
     */
    encoding: pulumi.Input<string>;
    /**
     * The S3 bucket and optional prefix where Audit Log events are written, using the format `s3://bucket[/prefix]`.
     */
    endpoint: pulumi.Input<string>;
    /**
     * The canned ACL sent when writing objects. Can be `private`, `bucket-owner-read`, or `bucket-owner-full-control`.
     */
    objectAcl?: pulumi.Input<string>;
    /**
     * The AWS region containing the S3 bucket.
     */
    region: pulumi.Input<string>;
    /**
     * The ARN of the AWS IAM role Vercel assumes to write objects.
     */
    roleArn: pulumi.Input<string>;
    /**
     * The server-side encryption header sent when writing objects. Can be `AES256`, `aws:kms`, or `aws:kms:dsse`.
     */
    serverSideEncryption?: pulumi.Input<string>;
}

export interface BulkRedirectsRedirect {
    /**
     * Whether the source match is case-sensitive.
     */
    caseSensitive?: pulumi.Input<boolean>;
    /**
     * The destination pathname or URL to redirect to.
     */
    destination: pulumi.Input<string>;
    /**
     * Whether query parameters are considered when matching the redirect.
     */
    query?: pulumi.Input<boolean>;
    /**
     * The source pathname to match.
     */
    source: pulumi.Input<string>;
    /**
     * The HTTP status code for the redirect.
     */
    statusCode: pulumi.Input<number>;
}

export interface CustomEnvironmentBranchTracking {
    /**
     * The pattern of the branch name to track.
     */
    pattern: pulumi.Input<string>;
    /**
     * How a branch name should be matched against the pattern. Must be one of 'startsWith', 'endsWith' or 'equals'.
     */
    type: pulumi.Input<string>;
}

export interface DeploymentProjectSettings {
    /**
     * The build command for this deployment. If omitted, this value will be taken from the project or automatically detected.
     */
    buildCommand?: pulumi.Input<string>;
    /**
     * The framework that is being used for this deployment. If omitted, no framework is selected.
     */
    framework?: pulumi.Input<string>;
    /**
     * The install command for this deployment. If omitted, this value will be taken from the project or automatically detected.
     */
    installCommand?: pulumi.Input<string>;
    /**
     * The output directory of the deployment. If omitted, this value will be taken from the project or automatically detected.
     */
    outputDirectory?: pulumi.Input<string>;
    /**
     * The name of a directory or relative path to the source code of your project. When null is used it will default to the project root.
     */
    rootDirectory?: pulumi.Input<string>;
}

export interface DnsRecordSrv {
    /**
     * The TCP or UDP port on which the service is to be found.
     */
    port: pulumi.Input<number>;
    /**
     * The priority of the target host, lower value means more preferred.
     */
    priority: pulumi.Input<number>;
    /**
     * The canonical hostname of the machine providing the service, ending in a dot.
     */
    target: pulumi.Input<string>;
    /**
     * A relative weight for records with the same priority, higher value means higher chance of getting picked.
     */
    weight: pulumi.Input<number>;
}

export interface FeatureFlagConfigDevelopment {
    /**
     * The variant to serve when this environment is enabled and no rules match.
     */
    defaultVariantId: pulumi.Input<string>;
    /**
     * The variant to serve while this environment is disabled or paused.
     */
    disabledVariantId: pulumi.Input<string>;
    /**
     * Whether the flag should actively evaluate in this environment.
     */
    enabled?: pulumi.Input<boolean>;
}

export interface FeatureFlagConfigPreview {
    /**
     * The variant to serve when this environment is enabled and no rules match.
     */
    defaultVariantId: pulumi.Input<string>;
    /**
     * The variant to serve while this environment is disabled or paused.
     */
    disabledVariantId: pulumi.Input<string>;
    /**
     * Whether the flag should actively evaluate in this environment.
     */
    enabled?: pulumi.Input<boolean>;
}

export interface FeatureFlagConfigProduction {
    /**
     * The variant to serve when this environment is enabled and no rules match.
     */
    defaultVariantId: pulumi.Input<string>;
    /**
     * The variant to serve while this environment is disabled or paused.
     */
    disabledVariantId: pulumi.Input<string>;
    /**
     * Whether the flag should actively evaluate in this environment.
     */
    enabled?: pulumi.Input<boolean>;
}

export interface FeatureFlagDefinitionVariant {
    /**
     * A human-readable description for the variant.
     */
    description?: pulumi.Input<string>;
    /**
     * The stable variant identifier referenced by flag configuration.
     */
    id: pulumi.Input<string>;
    /**
     * A human-readable label for the variant.
     */
    label?: pulumi.Input<string>;
    /**
     * The boolean value for this variant. Use this when `kind = "boolean"`.
     */
    valueBool?: pulumi.Input<boolean>;
    /**
     * The numeric value for this variant. Use this when `kind = "number"`.
     */
    valueNumber?: pulumi.Input<number>;
    /**
     * The string value for this variant. Use this when `kind = "string"`.
     */
    valueString?: pulumi.Input<string>;
}

export interface FeatureFlagSegmentExclude {
    /**
     * The entity attribute to match, for example `email`.
     */
    attribute: pulumi.Input<string>;
    /**
     * The entity type to match, for example `user`.
     */
    entity: pulumi.Input<string>;
    /**
     * The exact values to include or exclude for this entity attribute.
     */
    values: pulumi.Input<pulumi.Input<string>[]>;
}

export interface FeatureFlagSegmentInclude {
    /**
     * The entity attribute to match, for example `email`.
     */
    attribute: pulumi.Input<string>;
    /**
     * The entity type to match, for example `user`.
     */
    entity: pulumi.Input<string>;
    /**
     * The exact values to include or exclude for this entity attribute.
     */
    values: pulumi.Input<pulumi.Input<string>[]>;
}

export interface FirewallConfigIpRules {
    rules?: pulumi.Input<pulumi.Input<inputs.FirewallConfigIpRulesRule>[]>;
}

export interface FirewallConfigIpRulesRule {
    action: pulumi.Input<string>;
    /**
     * Hosts to apply these rules to
     */
    hostname: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    /**
     * IP or CIDR to block
     */
    ip: pulumi.Input<string>;
    notes?: pulumi.Input<string>;
}

export interface FirewallConfigManagedRulesets {
    /**
     * Enable the ai*bots managed ruleset and select action
     */
    aiBots?: pulumi.Input<inputs.FirewallConfigManagedRulesetsAiBots>;
    /**
     * DEPRECATED: Use bot*protection instead. This block will be removed in a future release.
     *
     * @deprecated The 'bot_filter' block is deprecated. Please use 'bot_protection' instead.
     */
    botFilter?: pulumi.Input<inputs.FirewallConfigManagedRulesetsBotFilter>;
    /**
     * Enable the bot*protection managed ruleset and select action
     */
    botProtection?: pulumi.Input<inputs.FirewallConfigManagedRulesetsBotProtection>;
    /**
     * Enable the owasp managed rulesets and select ruleset behaviors
     */
    owasp?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwasp>;
}

export interface FirewallConfigManagedRulesetsAiBots {
    action?: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsBotFilter {
    action?: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsBotProtection {
    action?: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwasp {
    /**
     * Generic Attack Detection
     */
    gen?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspGen>;
    /**
     * Java Attack Detection
     */
    java?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspJava>;
    /**
     * Local File Inclusion Rules
     */
    lfi?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspLfi>;
    /**
     * Multipart Rules
     */
    ma?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspMa>;
    /**
     * PHP Attack Detection
     */
    php?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspPhp>;
    /**
     * Remote Code Execution Rules
     */
    rce?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspRce>;
    /**
     * Remote File Inclusion Rules
     */
    rfi?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspRfi>;
    /**
     * Scanner Detection Rules
     */
    sd?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspSd>;
    /**
     * Session Fixation Attack
     */
    sf?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspSf>;
    /**
     * SQL Injection Rules
     */
    sqli?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspSqli>;
    /**
     * Cross Site Scripting Rules
     */
    xss?: pulumi.Input<inputs.FirewallConfigManagedRulesetsOwaspXss>;
}

export interface FirewallConfigManagedRulesetsOwaspGen {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspJava {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspLfi {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspMa {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspPhp {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspRce {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspRfi {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspSd {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspSf {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspSqli {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigManagedRulesetsOwaspXss {
    action: pulumi.Input<string>;
    active?: pulumi.Input<boolean>;
}

export interface FirewallConfigRules {
    rules?: pulumi.Input<pulumi.Input<inputs.FirewallConfigRulesRule>[]>;
}

export interface FirewallConfigRulesRule {
    /**
     * Actions to take when the condition groups match a request
     */
    action: pulumi.Input<inputs.FirewallConfigRulesRuleAction>;
    /**
     * Rule is active or disabled
     */
    active?: pulumi.Input<boolean>;
    /**
     * Sets of conditions that may match a request
     */
    conditionGroups: pulumi.Input<pulumi.Input<inputs.FirewallConfigRulesRuleConditionGroup>[]>;
    description?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    /**
     * Name to identify the rule
     */
    name: pulumi.Input<string>;
}

export interface FirewallConfigRulesRuleAction {
    /**
     * Base action
     */
    action: pulumi.Input<string>;
    /**
     * Forward persistence of a rule action
     */
    actionDuration?: pulumi.Input<string>;
    /**
     * Behavior or a rate limiting action. Required if action is rate*limit
     */
    rateLimit?: pulumi.Input<inputs.FirewallConfigRulesRuleActionRateLimit>;
    /**
     * How to redirect a request. Required if action is redirect
     */
    redirect?: pulumi.Input<inputs.FirewallConfigRulesRuleActionRedirect>;
}

export interface FirewallConfigRulesRuleActionRateLimit {
    /**
     * Action to take when rate limit is exceeded
     */
    action: pulumi.Input<string>;
    /**
     * Rate limiting algorithm
     */
    algo: pulumi.Input<string>;
    /**
     * Keys used to bucket an individual client
     */
    keys: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * number of requests allowed in the window
     */
    limit: pulumi.Input<number>;
    /**
     * Time window in seconds
     */
    window: pulumi.Input<number>;
}

export interface FirewallConfigRulesRuleActionRedirect {
    location: pulumi.Input<string>;
    permanent: pulumi.Input<boolean>;
}

export interface FirewallConfigRulesRuleConditionGroup {
    /**
     * Conditions that must all match within a group
     */
    conditions: pulumi.Input<pulumi.Input<inputs.FirewallConfigRulesRuleConditionGroupCondition>[]>;
}

export interface FirewallConfigRulesRuleConditionGroupCondition {
    /**
     * Key within type to match against
     */
    key?: pulumi.Input<string>;
    /**
     * Negate the condition. Defaults to false.
     */
    neg?: pulumi.Input<boolean>;
    /**
     * Operator to use for comparison. Options: `re` (regex), `eq` (equals), `neq` (not equals), `ex` (exists), `nex` (not exists), `inc` (includes), `ninc` (not includes), `pre` (prefix), `suf` (suffix), `sub` (substring), `gt` (greater than), `gte` (greater than or equal), `lt` (less than), `lte` (less than or equal). Note: `ex` and `nex` don't require a `value` field, only `key`.
     */
    op: pulumi.Input<string>;
    /**
     * Request key type to match against
     */
    type: pulumi.Input<string>;
    /**
     * Value to match against. Not required for existence operators (`ex`, `nex`). Use `values` instead for `inc` and `ninc` operators.
     */
    value?: pulumi.Input<string>;
    /**
     * Values to match against if op is inc, ninc
     */
    values?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface KmsIssuerSigningKey {
    /**
     * The signing algorithm of the key.
     */
    algorithm?: pulumi.Input<string>;
    /**
     * The key's self-signed X.509 certificate in PEM form.
     */
    certificatePem?: pulumi.Input<string>;
    /**
     * The time the key was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * The caller-supplied key ID (`kid`) for an imported key, or `null` for keys generated by Vercel. This is the value that appears in the JWKS and signed-token headers for imported keys.
     */
    importKeyId?: pulumi.Input<string>;
    /**
     * The ID of the issuer the key belongs to.
     */
    issuerId?: pulumi.Input<string>;
    /**
     * The server-minted addressable ID of the signing key. For keys generated by Vercel this is also the JWT/JWKS `kid`; for an imported key the `kid` may differ from this addressable ID.
     */
    keyId?: pulumi.Input<string>;
    /**
     * The fingerprint of the public key.
     */
    publicKeyFingerprint?: pulumi.Input<string>;
    /**
     * The public key as a JSON-encoded JWK.
     */
    publicKeyJwk?: pulumi.Input<string>;
    /**
     * The public key in SPKI PEM form.
     */
    publicKeyPem?: pulumi.Input<string>;
    /**
     * The time at which the key is scheduled to be revoked, if any.
     */
    revokeAt?: pulumi.Input<string>;
    /**
     * The status of the key, one of `pending`, `active`, or `revoking`. A newly rotated key is `pending` until its public key propagates, then becomes `active`.
     */
    status?: pulumi.Input<string>;
    /**
     * The time the key was last updated.
     */
    updatedAt?: pulumi.Input<string>;
}

export interface MicrofrontendGroupDefaultApp {
    /**
     * The default route for the project. Used for the screenshot of deployments.
     */
    defaultRoute?: pulumi.Input<string>;
    /**
     * The unique identifier for this resource. Format: team*id/microfrontend*group_id.
     */
    id?: pulumi.Input<string>;
    /**
     * The ID of the project.
     */
    projectId: pulumi.Input<string>;
}

export interface NetworkTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string>;
}

export interface OidcFederationPolicyClaim {
    /**
     * The OIDC claim name.
     */
    name: pulumi.Input<string>;
    /**
     * Values accepted for this claim. A claim matches when any configured value matches.
     */
    values: pulumi.Input<pulumi.Input<inputs.OidcFederationPolicyClaimValue>[]>;
}

export interface OidcFederationPolicyClaimValue {
    /**
     * The accepted claim value or wildcard pattern.
     */
    value: pulumi.Input<string>;
    /**
     * Whether `*` characters in the value should be interpreted as wildcards.
     */
    wildcards?: pulumi.Input<boolean>;
}

export interface OidcFederationPolicyResources {
    /**
     * Project IDs in the resource boundary. Use `["*"]` for all current and future team projects, or an empty set for no projects.
     */
    projectIds: pulumi.Input<pulumi.Input<string>[]>;
}

export interface ProjectDomainVerification {
    /**
     * The domain name on which the DNS record must be created.
     */
    domain?: pulumi.Input<string>;
    /**
     * A human-readable explanation of why this challenge was issued.
     */
    reason?: pulumi.Input<string>;
    /**
     * The type of DNS record that must be created to satisfy the challenge (e.g. `TXT`).
     */
    type?: pulumi.Input<string>;
    /**
     * The value that the DNS record must contain.
     */
    value?: pulumi.Input<string>;
}

export interface ProjectEnvironment {
    /**
     * A comment explaining what the environment variable is for.
     */
    comment?: pulumi.Input<string>;
    /**
     * The IDs of Custom Environments that the Environment Variable should be present on. At least one of `target` or `customEnvironmentIds` must be set.
     */
    customEnvironmentIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The git branch of the Environment Variable.
     */
    gitBranch?: pulumi.Input<string>;
    /**
     * The ID of the Environment Variable.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the Environment Variable.
     */
    key: pulumi.Input<string>;
    /**
     * Whether the Environment Variable is sensitive (meaning it cannot be read via the API or Vercel Dashboard once set). This must be explicitly set. If a [team-wide environment variable policy](https://vercel.com/docs/projects/environment-variables/sensitive-environment-variables#environment-variables-policy) is active, environment variables may have to be sensitive. Variables targeting only `development` must set this to `false`. Variables targeting `preview`, `production`, or custom environments may have to set this to `true`. A variable cannot target `development` together with `preview`, `production`, or custom environments while that team policy is enabled.
     */
    sensitive: pulumi.Input<boolean>;
    /**
     * The environments that the Environment Variable should be present on. Valid targets are either `production`, `preview`, or `development`. At least one of `target` or `customEnvironmentIds` must be set.
     */
    targets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The value of the Environment Variable.
     */
    value: pulumi.Input<string>;
}

export interface ProjectEnvironmentVariablesVariable {
    /**
     * A comment explaining what the environment variable is for.
     */
    comment?: pulumi.Input<string>;
    /**
     * The IDs of Custom Environments that the Environment Variable should be present on. At least one of `target` or `customEnvironmentIds` must be set.
     */
    customEnvironmentIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The git branch of the Environment Variable.
     */
    gitBranch?: pulumi.Input<string>;
    /**
     * The ID of the Environment Variable.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the Environment Variable.
     */
    key: pulumi.Input<string>;
    /**
     * Whether the Environment Variable is sensitive (meaning it cannot be read via the API or Vercel Dashboard once set). This must be explicitly set. If a team-wide environment variable policy is active, environment variables may have to be sensitive. Variables targeting only `development` must set this to `false`. Variables targeting `preview`, `production`, or custom environments may have to set this to `true`. A variable cannot target `development` together with `preview`, `production`, or custom environments while that team policy is enabled.
     */
    sensitive: pulumi.Input<boolean>;
    /**
     * The environments that the Environment Variable should be present on. Valid targets are either `production`, `preview`, or `development`. At least one of `target` or `customEnvironmentIds` must be set.
     */
    targets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The value of the Environment Variable.
     */
    value: pulumi.Input<string>;
}

export interface ProjectGitComments {
    /**
     * Whether Commit comments are enabled
     */
    onCommit: pulumi.Input<boolean>;
    /**
     * Whether Pull Request comments are enabled
     */
    onPullRequest: pulumi.Input<boolean>;
}

export interface ProjectGitProviderOptions {
    /**
     * **Beta:** Configuration for consolidated git commit status reporting. When enabled, Vercel posts a single consolidated commit status instead of one per deployment. This feature is in beta and may change in backwards-incompatible ways.
     */
    consolidatedGitCommitStatus?: pulumi.Input<inputs.ProjectGitProviderOptionsConsolidatedGitCommitStatus>;
    /**
     * Whether to create deployments
     */
    createDeployments?: pulumi.Input<boolean>;
    /**
     * Whether Vercel should post git commit statuses for this project. Defaults to `true` when unset.
     */
    gitCommitStatus?: pulumi.Input<boolean>;
    /**
     * Whether to enable repository dispatch events
     */
    repositoryDispatchEvents?: pulumi.Input<boolean>;
    /**
     * Whether to require verified commits
     */
    requireVerifiedCommits?: pulumi.Input<boolean>;
}

export interface ProjectGitProviderOptionsConsolidatedGitCommitStatus {
    /**
     * **Beta:** Whether consolidated commit status is enabled.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * **Beta:** Whether to propagate individual deployment failures to the consolidated status.
     */
    propagateFailures: pulumi.Input<boolean>;
}

export interface ProjectGitRepository {
    /**
     * Deploy hooks are unique URLs that allow you to trigger a deployment of a given branch. See https://vercel.com/docs/deployments/deploy-hooks for full information.
     */
    deployHooks?: pulumi.Input<pulumi.Input<inputs.ProjectGitRepositoryDeployHook>[]>;
    /**
     * By default, every commit pushed to the main branch will trigger a Production Deployment instead of the usual Preview Deployment. You can switch to a different branch here.
     */
    productionBranch?: pulumi.Input<string>;
    /**
     * The name of the git repository. For example: `vercel/next.js`.
     */
    repo: pulumi.Input<string>;
    /**
     * The git provider of the repository. Must be either `github`, `gitlab`, or `bitbucket`.
     */
    type: pulumi.Input<string>;
}

export interface ProjectGitRepositoryDeployHook {
    /**
     * The ID of the deploy hook.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the deploy hook.
     */
    name: pulumi.Input<string>;
    /**
     * The branch or commit hash that should be deployed.
     */
    ref: pulumi.Input<string>;
    /**
     * A URL that, when a POST request is made to, will trigger a new deployment.
     */
    url?: pulumi.Input<string>;
}

export interface ProjectMembersMember {
    /**
     * The email of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     */
    email?: pulumi.Input<string>;
    /**
     * The role that the user should have in the project. One of 'ADMIN', 'PROJECT*DEVELOPER', or 'PROJECT*VIEWER'.
     */
    role: pulumi.Input<string>;
    /**
     * The ID of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     */
    userId?: pulumi.Input<string>;
    /**
     * The username of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     */
    username?: pulumi.Input<string>;
}

export interface ProjectOidcTokenConfig {
    /**
     * Configures the URL of the `iss` claim. `team` = `https://oidc.vercel.com/[teamSlug]` `global` = `https://oidc.vercel.com`
     */
    issuerMode?: pulumi.Input<string>;
}

export interface ProjectOptionsAllowlist {
    /**
     * The allowed paths for the OPTIONS Allowlist. Incoming requests will bypass Deployment Protection if they have the method `OPTIONS` and **start with** one of the path values.
     */
    paths: pulumi.Input<pulumi.Input<inputs.ProjectOptionsAllowlistPath>[]>;
}

export interface ProjectOptionsAllowlistPath {
    /**
     * The path prefix to compare with the incoming request path.
     */
    value: pulumi.Input<string>;
}

export interface ProjectPasswordProtection {
    /**
     * The deployment environment to protect. Must be one of `standardProtectionNew` (Standard Protection), `standardProtection` (Legacy Standard Protection), `allDeployments`, or `onlyPreviewDeployments`.
     */
    deploymentType: pulumi.Input<string>;
    /**
     * The password that visitors must enter to gain access to your Preview Deployments. Drift detection is not possible for this field.
     */
    password: pulumi.Input<string>;
}

export interface ProjectResourceConfig {
    /**
     * Enable fluid compute for your Vercel Functions to automatically manage concurrency and optimize performance. Vercel will handle the defaults to ensure the best experience for your workload.
     */
    fluid?: pulumi.Input<boolean>;
    /**
     * The amount of CPU available to your Serverless Functions. Should be one of 'standard_legacy' (0.6vCPU), 'standard' (1vCPU) or 'performance' (1.7vCPUs).
     */
    functionDefaultCpuType?: pulumi.Input<string>;
    /**
     * The default regions for Serverless Functions. Must be an array of valid region identifiers.
     */
    functionDefaultRegions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The default timeout for Serverless Functions.
     */
    functionDefaultTimeout?: pulumi.Input<number>;
}

export interface ProjectRollingReleaseStage {
    /**
     * The duration in minutes to wait before advancing to the next stage. Required for automatic advancement type.
     */
    duration?: pulumi.Input<number>;
    /**
     * The percentage of traffic to route to this stage.
     */
    targetPercentage: pulumi.Input<number>;
}

export interface ProjectRoutePosition {
    /**
     * Where to place the rule. One of `start`, `end`, `before`, or `after`.
     */
    placement: pulumi.Input<string>;
    /**
     * The existing route ID to place this rule before or after.
     */
    referenceRouteId?: pulumi.Input<string>;
}

export interface ProjectRouteRoute {
    /**
     * Whether the `src` matcher is case-sensitive.
     */
    caseSensitive?: pulumi.Input<boolean>;
    /**
     * The destination for rewrites or redirects.
     */
    dest?: pulumi.Input<string>;
    /**
     * Conditions that must be present for the rule to match.
     */
    has?: pulumi.Input<pulumi.Input<inputs.ProjectRouteRouteHa>[]>;
    /**
     * Headers to set for the matched request.
     */
    headers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Conditions that must be absent for the rule to match.
     */
    missings?: pulumi.Input<pulumi.Input<inputs.ProjectRouteRouteMissing>[]>;
    /**
     * Whether the rule should respect cache control headers from the origin.
     */
    respectOriginCacheControl?: pulumi.Input<boolean>;
    /**
     * The source pattern to match.
     */
    src: pulumi.Input<string>;
    /**
     * The HTTP status code to set for redirects or status-only rules.
     */
    status?: pulumi.Input<number>;
    /**
     * Transforms applied to the request or response when the rule matches.
     */
    transforms?: pulumi.Input<pulumi.Input<inputs.ProjectRouteRouteTransform>[]>;
}

export interface ProjectRouteRouteHa {
    /**
     * The key to match for `header`, `cookie`, or `query` conditions.
     */
    key?: pulumi.Input<string>;
    /**
     * The condition type. One of `host`, `header`, `cookie`, or `query`.
     */
    type: pulumi.Input<string>;
    /**
     * The value to match.
     */
    value?: pulumi.Input<string>;
}

export interface ProjectRouteRouteMissing {
    /**
     * The key to match for `header`, `cookie`, or `query` conditions.
     */
    key?: pulumi.Input<string>;
    /**
     * The condition type. One of `host`, `header`, `cookie`, or `query`.
     */
    type: pulumi.Input<string>;
    /**
     * The value to match.
     */
    value?: pulumi.Input<string>;
}

export interface ProjectRouteRouteTransform {
    /**
     * A JSON document containing transform arguments. Prefer `jsonencode(...)` when setting this.
     */
    args?: pulumi.Input<string>;
    /**
     * Environment names that gate this transform.
     */
    envs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The transform operation. One of `append`, `set`, or `delete`.
     */
    op: pulumi.Input<string>;
    /**
     * A JSON document describing the transform target. Prefer `jsonencode(...)` when setting this.
     */
    target?: pulumi.Input<string>;
    /**
     * The transform target. One of `request.headers`, `request.query`, or `response.headers`.
     */
    type: pulumi.Input<string>;
}

export interface ProjectTracingSamplingRule {
    /**
     * Environment to apply this sampling rule to. Can be `production` or `preview`.
     */
    environment?: pulumi.Input<string>;
    /**
     * Sampling rate from 0 to 1.
     */
    rate: pulumi.Input<number>;
    /**
     * Request path prefix to apply this sampling rule to.
     */
    requestPath?: pulumi.Input<string>;
}

export interface ProjectTrustedIps {
    /**
     * The allowed IP addressses and CIDR ranges with optional descriptions.
     */
    addresses: pulumi.Input<pulumi.Input<inputs.ProjectTrustedIpsAddress>[]>;
    /**
     * The deployment environment to protect. Must be one of `standardProtectionNew` (Standard Protection), `standardProtection` (Legacy Standard Protection), `allDeployments`, `onlyProductionDeployments`, or `onlyPreviewDeployments`.
     */
    deploymentType: pulumi.Input<string>;
    /**
     * Whether or not Trusted IPs is optional to access a deployment. Must be either `trustedIpRequired` or `trustedIpOptional`. `trustedIpOptional` is only available with Standalone Trusted IPs.
     */
    protectionMode?: pulumi.Input<string>;
}

export interface ProjectTrustedIpsAddress {
    /**
     * A description for the value
     */
    note?: pulumi.Input<string>;
    /**
     * The address or CIDR range that can access deployments.
     */
    value: pulumi.Input<string>;
}

export interface ProjectTrustedSources {
    /**
     * External sources that can reach this project's protected deployments using short-lived OIDC tokens.
     */
    externalSources?: pulumi.Input<pulumi.Input<inputs.ProjectTrustedSourcesExternalSource>[]>;
    /**
     * Vercel projects in the same team that can reach this project's protected deployments.
     */
    projects?: pulumi.Input<pulumi.Input<inputs.ProjectTrustedSourcesProject>[]>;
}

export interface ProjectTrustedSourcesExternalSource {
    /**
     * Claims that must match on the OIDC token. Each key is a claim name, and each value is a set of accepted values. The API requires `aud` and issuer-specific identity claims.
     */
    claims: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>}>;
    /**
     * The OIDC issuer URL.
     */
    issuer: pulumi.Input<string>;
    /**
     * A label or description for the trusted external source entry.
     */
    label?: pulumi.Input<string>;
    /**
     * The target environments on this project that may be accessed.
     */
    to: pulumi.Input<inputs.ProjectTrustedSourcesExternalSourceTo>;
}

export interface ProjectTrustedSourcesExternalSourceTo {
    /**
     * Named environment preset. Currently only `all-custom` is supported.
     */
    preset?: pulumi.Input<string>;
    /**
     * System environment slugs (`production`, `preview`, `development`) or custom environment slugs.
     */
    slugs?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface ProjectTrustedSourcesProject {
    /**
     * Optional overrides for default same-environment matching. Saved rules replace the API defaults for this trusted project.
     */
    customAllows?: pulumi.Input<pulumi.Input<inputs.ProjectTrustedSourcesProjectCustomAllow>[]>;
    /**
     * A label or description for the trusted project.
     */
    label?: pulumi.Input<string>;
    /**
     * The trusted Vercel project ID.
     */
    projectId: pulumi.Input<string>;
}

export interface ProjectTrustedSourcesProjectCustomAllow {
    /**
     * The source environments on the trusted project that are allowed to access the target environments.
     */
    from: pulumi.Input<inputs.ProjectTrustedSourcesProjectCustomAllowFrom>;
    /**
     * The target environments on this project that may be accessed.
     */
    to: pulumi.Input<inputs.ProjectTrustedSourcesProjectCustomAllowTo>;
}

export interface ProjectTrustedSourcesProjectCustomAllowFrom {
    /**
     * Named environment preset. Currently only `all-custom` is supported.
     */
    preset?: pulumi.Input<string>;
    /**
     * System environment slugs (`production`, `preview`, `development`) or custom environment slugs.
     */
    slugs?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface ProjectTrustedSourcesProjectCustomAllowTo {
    /**
     * Named environment preset. Currently only `all-custom` is supported.
     */
    preset?: pulumi.Input<string>;
    /**
     * System environment slugs (`production`, `preview`, `development`) or custom environment slugs.
     */
    slugs?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface ProjectVercelAuthentication {
    /**
     * The deployment environment to protect. The default value is `standardProtectionNew` (Standard Protection). Must be one of `standardProtectionNew` (Standard Protection), `standardProtection` (Legacy Standard Protection), `allDeployments`, `onlyPreviewDeployments`, or `none`.
     */
    deploymentType?: pulumi.Input<string>;
}

export interface TeamConfigRemoteCaching {
    /**
     * Indicates if Remote Caching is enabled.
     */
    enabled?: pulumi.Input<boolean>;
}

export interface TeamConfigSaml {
    /**
     * Indicates if SAML is enforced for the team.
     */
    enforced?: pulumi.Input<boolean>;
    /**
     * Directory groups to role or access group mappings. For each directory group, specify either a role or access group id.
     */
    roles?: pulumi.Input<{[key: string]: pulumi.Input<inputs.TeamConfigSamlRoles>}>;
}

export interface TeamConfigSamlRoles {
    /**
     * The access group id to assign to the user.
     */
    accessGroupId?: pulumi.Input<string>;
    /**
     * The team level role to assign to the user. One of 'MEMBER', 'OWNER', 'VIEWER', 'DEVELOPER', 'BILLING' or 'CONTRIBUTOR'.
     */
    role?: pulumi.Input<string>;
}

export interface TeamMemberProject {
    /**
     * The ID of the project that the user should be granted access to.
     */
    projectId: pulumi.Input<string>;
    /**
     * The role that the user should have in the project.
     */
    role: pulumi.Input<string>;
}

export interface TraceDrainSamplingRule {
    /**
     * Environment to apply this sampling rule to. Can be `production` or `preview`.
     */
    environment?: pulumi.Input<string>;
    /**
     * Sampling rate from 0 to 1.
     */
    rate: pulumi.Input<number>;
    /**
     * Request path prefix to apply this sampling rule to.
     */
    requestPath?: pulumi.Input<string>;
}
