// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel.Inputs
{

    public sealed class DeploymentProjectSettingsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("buildCommand")]
        public Input<string>? BuildCommand { get; set; }

        [Input("framework")]
        public Input<string>? Framework { get; set; }

        [Input("installCommand")]
        public Input<string>? InstallCommand { get; set; }

        [Input("outputDirectory")]
        public Input<string>? OutputDirectory { get; set; }

        [Input("rootDirectory")]
        public Input<string>? RootDirectory { get; set; }

        public DeploymentProjectSettingsGetArgs()
        {
        }
        public static new DeploymentProjectSettingsGetArgs Empty => new DeploymentProjectSettingsGetArgs();
    }
}
