// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel.Inputs
{

    public sealed class FeatureFlagSegmentIncludeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The entity attribute to match, for example `Email`.
        /// </summary>
        [Input("attribute", required: true)]
        public Input<string> Attribute { get; set; } = null!;

        /// <summary>
        /// The entity type to match, for example `User`.
        /// </summary>
        [Input("entity", required: true)]
        public Input<string> Entity { get; set; } = null!;

        [Input("values", required: true)]
        private InputList<string>? _values;

        /// <summary>
        /// The exact values to include or exclude for this entity attribute.
        /// </summary>
        public InputList<string> Values
        {
            get => _values ?? (_values = new InputList<string>());
            set => _values = value;
        }

        public FeatureFlagSegmentIncludeGetArgs()
        {
        }
        public static new FeatureFlagSegmentIncludeGetArgs Empty => new FeatureFlagSegmentIncludeGetArgs();
    }
}
