// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vercel.Inputs
{

    public sealed class ProjectVercelAuthenticationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("protectProduction")]
        public Input<bool>? ProtectProduction { get; set; }

        public ProjectVercelAuthenticationGetArgs()
        {
        }
        public static new ProjectVercelAuthenticationGetArgs Empty => new ProjectVercelAuthenticationGetArgs();
    }
}
