// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Vercel.Inputs
{

    public sealed class TeamConfigDefaultDeploymentProtectionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Default Vercel Authentication for new projects.
        /// </summary>
        [Input("vercelAuthentication", required: true)]
        public Input<Inputs.TeamConfigDefaultDeploymentProtectionVercelAuthenticationGetArgs> VercelAuthentication { get; set; } = null!;

        public TeamConfigDefaultDeploymentProtectionGetArgs()
        {
        }
        public static new TeamConfigDefaultDeploymentProtectionGetArgs Empty => new TeamConfigDefaultDeploymentProtectionGetArgs();
    }
}
