// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAttackChallengeModeArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAttackChallengeModeArgs Empty = new GetAttackChallengeModeArgs();

    /**
     * The ID of the Project to adjust the CPU for.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return The ID of the Project to adjust the CPU for.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * The ID of the team the Project exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return The ID of the team the Project exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    private GetAttackChallengeModeArgs() {}

    private GetAttackChallengeModeArgs(GetAttackChallengeModeArgs $) {
        this.projectId = $.projectId;
        this.teamId = $.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAttackChallengeModeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAttackChallengeModeArgs $;

        public Builder() {
            $ = new GetAttackChallengeModeArgs();
        }

        public Builder(GetAttackChallengeModeArgs defaults) {
            $ = new GetAttackChallengeModeArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param projectId The ID of the Project to adjust the CPU for.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the Project to adjust the CPU for.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param teamId The ID of the team the Project exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId The ID of the team the Project exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        public GetAttackChallengeModeArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetAttackChallengeModeArgs", "projectId");
            }
            return $;
        }
    }

}
