// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAttackChallengeModePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAttackChallengeModePlainArgs Empty = new GetAttackChallengeModePlainArgs();

    /**
     * The ID of the Project to adjust the CPU for.
     * 
     */
    @Import(name="projectId", required=true)
    private String projectId;

    /**
     * @return The ID of the Project to adjust the CPU for.
     * 
     */
    public String projectId() {
        return this.projectId;
    }

    /**
     * The ID of the team the Project exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable String teamId;

    /**
     * @return The ID of the team the Project exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<String> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    private GetAttackChallengeModePlainArgs() {}

    private GetAttackChallengeModePlainArgs(GetAttackChallengeModePlainArgs $) {
        this.projectId = $.projectId;
        this.teamId = $.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAttackChallengeModePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAttackChallengeModePlainArgs $;

        public Builder() {
            $ = new GetAttackChallengeModePlainArgs();
        }

        public Builder(GetAttackChallengeModePlainArgs defaults) {
            $ = new GetAttackChallengeModePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param projectId The ID of the Project to adjust the CPU for.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param teamId The ID of the team the Project exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable String teamId) {
            $.teamId = teamId;
            return this;
        }

        public GetAttackChallengeModePlainArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetAttackChallengeModePlainArgs", "projectId");
            }
            return $;
        }
    }

}
