// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetBlobStoreArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetBlobStoreArgs Empty = new GetBlobStoreArgs();

    /**
     * The ID of the Blob store.
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The ID of the Blob store.
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    /**
     * The ID of the team that owns the Blob store. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return The ID of the team that owns the Blob store. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    private GetBlobStoreArgs() {}

    private GetBlobStoreArgs(GetBlobStoreArgs $) {
        this.id = $.id;
        this.teamId = $.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetBlobStoreArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetBlobStoreArgs $;

        public Builder() {
            $ = new GetBlobStoreArgs();
        }

        public Builder(GetBlobStoreArgs defaults) {
            $ = new GetBlobStoreArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of the Blob store.
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The ID of the Blob store.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param teamId The ID of the team that owns the Blob store. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId The ID of the team that owns the Blob store. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        public GetBlobStoreArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetBlobStoreArgs", "id");
            }
            return $;
        }
    }

}
