// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetEdgeConfigTokenArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetEdgeConfigTokenArgs Empty = new GetEdgeConfigTokenArgs();

    /**
     * The label of the Edge Config Token.
     * 
     */
    @Import(name="edgeConfigId", required=true)
    private Output<String> edgeConfigId;

    /**
     * @return The label of the Edge Config Token.
     * 
     */
    public Output<String> edgeConfigId() {
        return this.edgeConfigId;
    }

    /**
     * The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    /**
     * A read access token used for authenticating against the Edge Config&#39;s endpoint for high volume, low-latency requests.
     * 
     */
    @Import(name="token", required=true)
    private Output<String> token;

    /**
     * @return A read access token used for authenticating against the Edge Config&#39;s endpoint for high volume, low-latency requests.
     * 
     */
    public Output<String> token() {
        return this.token;
    }

    private GetEdgeConfigTokenArgs() {}

    private GetEdgeConfigTokenArgs(GetEdgeConfigTokenArgs $) {
        this.edgeConfigId = $.edgeConfigId;
        this.teamId = $.teamId;
        this.token = $.token;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetEdgeConfigTokenArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetEdgeConfigTokenArgs $;

        public Builder() {
            $ = new GetEdgeConfigTokenArgs();
        }

        public Builder(GetEdgeConfigTokenArgs defaults) {
            $ = new GetEdgeConfigTokenArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param edgeConfigId The label of the Edge Config Token.
         * 
         * @return builder
         * 
         */
        public Builder edgeConfigId(Output<String> edgeConfigId) {
            $.edgeConfigId = edgeConfigId;
            return this;
        }

        /**
         * @param edgeConfigId The label of the Edge Config Token.
         * 
         * @return builder
         * 
         */
        public Builder edgeConfigId(String edgeConfigId) {
            return edgeConfigId(Output.of(edgeConfigId));
        }

        /**
         * @param teamId The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        /**
         * @param token A read access token used for authenticating against the Edge Config&#39;s endpoint for high volume, low-latency requests.
         * 
         * @return builder
         * 
         */
        public Builder token(Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token A read access token used for authenticating against the Edge Config&#39;s endpoint for high volume, low-latency requests.
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        public GetEdgeConfigTokenArgs build() {
            if ($.edgeConfigId == null) {
                throw new MissingRequiredPropertyException("GetEdgeConfigTokenArgs", "edgeConfigId");
            }
            if ($.token == null) {
                throw new MissingRequiredPropertyException("GetEdgeConfigTokenArgs", "token");
            }
            return $;
        }
    }

}
