// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetEdgeConfigItemArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetEdgeConfigItemArgs Empty = new GetEdgeConfigItemArgs();

    /**
     * The ID of the Edge Config that the item should exist under.
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The ID of the Edge Config that the item should exist under.
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    /**
     * The name of the key you want to retrieve within your Edge Config.
     * 
     */
    @Import(name="key", required=true)
    private Output<String> key;

    /**
     * @return The name of the key you want to retrieve within your Edge Config.
     * 
     */
    public Output<String> key() {
        return this.key;
    }

    /**
     * The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    private GetEdgeConfigItemArgs() {}

    private GetEdgeConfigItemArgs(GetEdgeConfigItemArgs $) {
        this.id = $.id;
        this.key = $.key;
        this.teamId = $.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetEdgeConfigItemArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetEdgeConfigItemArgs $;

        public Builder() {
            $ = new GetEdgeConfigItemArgs();
        }

        public Builder(GetEdgeConfigItemArgs defaults) {
            $ = new GetEdgeConfigItemArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of the Edge Config that the item should exist under.
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The ID of the Edge Config that the item should exist under.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param key The name of the key you want to retrieve within your Edge Config.
         * 
         * @return builder
         * 
         */
        public Builder key(Output<String> key) {
            $.key = key;
            return this;
        }

        /**
         * @param key The name of the key you want to retrieve within your Edge Config.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            return key(Output.of(key));
        }

        /**
         * @param teamId The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId The ID of the team the Edge Config should exist under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        public GetEdgeConfigItemArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetEdgeConfigItemArgs", "id");
            }
            if ($.key == null) {
                throw new MissingRequiredPropertyException("GetEdgeConfigItemArgs", "key");
            }
            return $;
        }
    }

}
