// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetProjectDirectoryPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetProjectDirectoryPlainArgs Empty = new GetProjectDirectoryPlainArgs();

    @Import(name="path", required=true)
    private String path;

    public String path() {
        return this.path;
    }

    private GetProjectDirectoryPlainArgs() {}

    private GetProjectDirectoryPlainArgs(GetProjectDirectoryPlainArgs $) {
        this.path = $.path;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetProjectDirectoryPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetProjectDirectoryPlainArgs $;

        public Builder() {
            $ = new GetProjectDirectoryPlainArgs();
        }

        public Builder(GetProjectDirectoryPlainArgs defaults) {
            $ = new GetProjectDirectoryPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder path(String path) {
            $.path = path;
            return this;
        }

        public GetProjectDirectoryPlainArgs build() {
            if ($.path == null) {
                throw new MissingRequiredPropertyException("GetProjectDirectoryPlainArgs", "path");
            }
            return $;
        }
    }

}
