// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetVcrRepositoryArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetVcrRepositoryArgs Empty = new GetVcrRepositoryArgs();

    /**
     * The name of the repository.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The name of the repository.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * The ID of the existing Vercel Project the repository belongs to.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return The ID of the existing Vercel Project the repository belongs to.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * The ID of the team the repository exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return The ID of the team the repository exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    private GetVcrRepositoryArgs() {}

    private GetVcrRepositoryArgs(GetVcrRepositoryArgs $) {
        this.name = $.name;
        this.projectId = $.projectId;
        this.teamId = $.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetVcrRepositoryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetVcrRepositoryArgs $;

        public Builder() {
            $ = new GetVcrRepositoryArgs();
        }

        public Builder(GetVcrRepositoryArgs defaults) {
            $ = new GetVcrRepositoryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the repository.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the repository.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param projectId The ID of the existing Vercel Project the repository belongs to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the existing Vercel Project the repository belongs to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param teamId The ID of the team the repository exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId The ID of the team the repository exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        public GetVcrRepositoryArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetVcrRepositoryArgs", "name");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetVcrRepositoryArgs", "projectId");
            }
            return $;
        }
    }

}
