// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KmsProjectGrantState extends com.pulumi.resources.ResourceArgs {

    public static final KmsProjectGrantState Empty = new KmsProjectGrantState();

    /**
     * The time the policy was created.
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return The time the policy was created.
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * The environments in which the project may request signed tokens (for example `production`, `preview`).
     * 
     */
    @Import(name="environments")
    private @Nullable Output<List<String>> environments;

    /**
     * @return The environments in which the project may request signed tokens (for example `production`, `preview`).
     * 
     */
    public Optional<Output<List<String>>> environments() {
        return Optional.ofNullable(this.environments);
    }

    /**
     * The ID of the issuer this policy is attached to.
     * 
     */
    @Import(name="issuerId")
    private @Nullable Output<String> issuerId;

    /**
     * @return The ID of the issuer this policy is attached to.
     * 
     */
    public Optional<Output<String>> issuerId() {
        return Optional.ofNullable(this.issuerId);
    }

    /**
     * The ID of the Vercel project being granted access.
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return The ID of the Vercel project being granted access.
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * The ID of the team the issuer exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return The ID of the team the issuer exists under. Required when configuring a team resource if a default team has not been set in the provider.
     * 
     */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    /**
     * Additional claims KMS should include in signed JWTs for this policy, as a JSON-encoded object.
     * 
     */
    @Import(name="tokenClaims")
    private @Nullable Output<String> tokenClaims;

    /**
     * @return Additional claims KMS should include in signed JWTs for this policy, as a JSON-encoded object.
     * 
     */
    public Optional<Output<String>> tokenClaims() {
        return Optional.ofNullable(this.tokenClaims);
    }

    /**
     * The time the policy was last updated.
     * 
     */
    @Import(name="updatedAt")
    private @Nullable Output<String> updatedAt;

    /**
     * @return The time the policy was last updated.
     * 
     */
    public Optional<Output<String>> updatedAt() {
        return Optional.ofNullable(this.updatedAt);
    }

    private KmsProjectGrantState() {}

    private KmsProjectGrantState(KmsProjectGrantState $) {
        this.createdAt = $.createdAt;
        this.environments = $.environments;
        this.issuerId = $.issuerId;
        this.projectId = $.projectId;
        this.teamId = $.teamId;
        this.tokenClaims = $.tokenClaims;
        this.updatedAt = $.updatedAt;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KmsProjectGrantState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KmsProjectGrantState $;

        public Builder() {
            $ = new KmsProjectGrantState();
        }

        public Builder(KmsProjectGrantState defaults) {
            $ = new KmsProjectGrantState(Objects.requireNonNull(defaults));
        }

        /**
         * @param createdAt The time the policy was created.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt The time the policy was created.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param environments The environments in which the project may request signed tokens (for example `production`, `preview`).
         * 
         * @return builder
         * 
         */
        public Builder environments(@Nullable Output<List<String>> environments) {
            $.environments = environments;
            return this;
        }

        /**
         * @param environments The environments in which the project may request signed tokens (for example `production`, `preview`).
         * 
         * @return builder
         * 
         */
        public Builder environments(List<String> environments) {
            return environments(Output.of(environments));
        }

        /**
         * @param environments The environments in which the project may request signed tokens (for example `production`, `preview`).
         * 
         * @return builder
         * 
         */
        public Builder environments(String... environments) {
            return environments(List.of(environments));
        }

        /**
         * @param issuerId The ID of the issuer this policy is attached to.
         * 
         * @return builder
         * 
         */
        public Builder issuerId(@Nullable Output<String> issuerId) {
            $.issuerId = issuerId;
            return this;
        }

        /**
         * @param issuerId The ID of the issuer this policy is attached to.
         * 
         * @return builder
         * 
         */
        public Builder issuerId(String issuerId) {
            return issuerId(Output.of(issuerId));
        }

        /**
         * @param projectId The ID of the Vercel project being granted access.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the Vercel project being granted access.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param teamId The ID of the team the issuer exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId The ID of the team the issuer exists under. Required when configuring a team resource if a default team has not been set in the provider.
         * 
         * @return builder
         * 
         */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        /**
         * @param tokenClaims Additional claims KMS should include in signed JWTs for this policy, as a JSON-encoded object.
         * 
         * @return builder
         * 
         */
        public Builder tokenClaims(@Nullable Output<String> tokenClaims) {
            $.tokenClaims = tokenClaims;
            return this;
        }

        /**
         * @param tokenClaims Additional claims KMS should include in signed JWTs for this policy, as a JSON-encoded object.
         * 
         * @return builder
         * 
         */
        public Builder tokenClaims(String tokenClaims) {
            return tokenClaims(Output.of(tokenClaims));
        }

        /**
         * @param updatedAt The time the policy was last updated.
         * 
         * @return builder
         * 
         */
        public Builder updatedAt(@Nullable Output<String> updatedAt) {
            $.updatedAt = updatedAt;
            return this;
        }

        /**
         * @param updatedAt The time the policy was last updated.
         * 
         * @return builder
         * 
         */
        public Builder updatedAt(String updatedAt) {
            return updatedAt(Output.of(updatedAt));
        }

        public KmsProjectGrantState build() {
            return $;
        }
    }

}
