// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectRouteRouteTransformArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectRouteRouteTransformArgs Empty = new ProjectRouteRouteTransformArgs();

    /**
     * A JSON document containing transform arguments. Prefer `jsonencode(...)` when setting this.
     * 
     */
    @Import(name="args")
    private @Nullable Output<String> args;

    /**
     * @return A JSON document containing transform arguments. Prefer `jsonencode(...)` when setting this.
     * 
     */
    public Optional<Output<String>> args() {
        return Optional.ofNullable(this.args);
    }

    /**
     * Environment names that gate this transform.
     * 
     */
    @Import(name="envs")
    private @Nullable Output<List<String>> envs;

    /**
     * @return Environment names that gate this transform.
     * 
     */
    public Optional<Output<List<String>>> envs() {
        return Optional.ofNullable(this.envs);
    }

    /**
     * The transform operation. One of `append`, `set`, or `delete`.
     * 
     */
    @Import(name="op", required=true)
    private Output<String> op;

    /**
     * @return The transform operation. One of `append`, `set`, or `delete`.
     * 
     */
    public Output<String> op() {
        return this.op;
    }

    /**
     * A JSON document describing the transform target. Prefer `jsonencode(...)` when setting this.
     * 
     */
    @Import(name="target")
    private @Nullable Output<String> target;

    /**
     * @return A JSON document describing the transform target. Prefer `jsonencode(...)` when setting this.
     * 
     */
    public Optional<Output<String>> target() {
        return Optional.ofNullable(this.target);
    }

    /**
     * The transform target. One of `request.headers`, `request.query`, or `response.headers`.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The transform target. One of `request.headers`, `request.query`, or `response.headers`.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private ProjectRouteRouteTransformArgs() {}

    private ProjectRouteRouteTransformArgs(ProjectRouteRouteTransformArgs $) {
        this.args = $.args;
        this.envs = $.envs;
        this.op = $.op;
        this.target = $.target;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectRouteRouteTransformArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectRouteRouteTransformArgs $;

        public Builder() {
            $ = new ProjectRouteRouteTransformArgs();
        }

        public Builder(ProjectRouteRouteTransformArgs defaults) {
            $ = new ProjectRouteRouteTransformArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param args A JSON document containing transform arguments. Prefer `jsonencode(...)` when setting this.
         * 
         * @return builder
         * 
         */
        public Builder args(@Nullable Output<String> args) {
            $.args = args;
            return this;
        }

        /**
         * @param args A JSON document containing transform arguments. Prefer `jsonencode(...)` when setting this.
         * 
         * @return builder
         * 
         */
        public Builder args(String args) {
            return args(Output.of(args));
        }

        /**
         * @param envs Environment names that gate this transform.
         * 
         * @return builder
         * 
         */
        public Builder envs(@Nullable Output<List<String>> envs) {
            $.envs = envs;
            return this;
        }

        /**
         * @param envs Environment names that gate this transform.
         * 
         * @return builder
         * 
         */
        public Builder envs(List<String> envs) {
            return envs(Output.of(envs));
        }

        /**
         * @param envs Environment names that gate this transform.
         * 
         * @return builder
         * 
         */
        public Builder envs(String... envs) {
            return envs(List.of(envs));
        }

        /**
         * @param op The transform operation. One of `append`, `set`, or `delete`.
         * 
         * @return builder
         * 
         */
        public Builder op(Output<String> op) {
            $.op = op;
            return this;
        }

        /**
         * @param op The transform operation. One of `append`, `set`, or `delete`.
         * 
         * @return builder
         * 
         */
        public Builder op(String op) {
            return op(Output.of(op));
        }

        /**
         * @param target A JSON document describing the transform target. Prefer `jsonencode(...)` when setting this.
         * 
         * @return builder
         * 
         */
        public Builder target(@Nullable Output<String> target) {
            $.target = target;
            return this;
        }

        /**
         * @param target A JSON document describing the transform target. Prefer `jsonencode(...)` when setting this.
         * 
         * @return builder
         * 
         */
        public Builder target(String target) {
            return target(Output.of(target));
        }

        /**
         * @param type The transform target. One of `request.headers`, `request.query`, or `response.headers`.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The transform target. One of `request.headers`, `request.query`, or `response.headers`.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ProjectRouteRouteTransformArgs build() {
            if ($.op == null) {
                throw new MissingRequiredPropertyException("ProjectRouteRouteTransformArgs", "op");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("ProjectRouteRouteTransformArgs", "type");
            }
            return $;
        }
    }

}
