// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.vercel.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectMembersMemberArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectMembersMemberArgs Empty = new ProjectMembersMemberArgs();

    /**
     * The email of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     * 
     */
    @Import(name="email")
    private @Nullable Output<String> email;

    /**
     * @return The email of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     * 
     */
    public Optional<Output<String>> email() {
        return Optional.ofNullable(this.email);
    }

    /**
     * The role that the user should have in the project. One of &#39;ADMIN&#39;, &#39;PROJECT*DEVELOPER&#39;, or &#39;PROJECT*VIEWER&#39;.
     * 
     */
    @Import(name="role", required=true)
    private Output<String> role;

    /**
     * @return The role that the user should have in the project. One of &#39;ADMIN&#39;, &#39;PROJECT*DEVELOPER&#39;, or &#39;PROJECT*VIEWER&#39;.
     * 
     */
    public Output<String> role() {
        return this.role;
    }

    /**
     * The ID of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     * 
     */
    @Import(name="userId")
    private @Nullable Output<String> userId;

    /**
     * @return The ID of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     * 
     */
    public Optional<Output<String>> userId() {
        return Optional.ofNullable(this.userId);
    }

    /**
     * The username of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     * 
     */
    @Import(name="username")
    private @Nullable Output<String> username;

    /**
     * @return The username of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
     * 
     */
    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private ProjectMembersMemberArgs() {}

    private ProjectMembersMemberArgs(ProjectMembersMemberArgs $) {
        this.email = $.email;
        this.role = $.role;
        this.userId = $.userId;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectMembersMemberArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectMembersMemberArgs $;

        public Builder() {
            $ = new ProjectMembersMemberArgs();
        }

        public Builder(ProjectMembersMemberArgs defaults) {
            $ = new ProjectMembersMemberArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param email The email of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
         * 
         * @return builder
         * 
         */
        public Builder email(@Nullable Output<String> email) {
            $.email = email;
            return this;
        }

        /**
         * @param email The email of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
         * 
         * @return builder
         * 
         */
        public Builder email(String email) {
            return email(Output.of(email));
        }

        /**
         * @param role The role that the user should have in the project. One of &#39;ADMIN&#39;, &#39;PROJECT*DEVELOPER&#39;, or &#39;PROJECT*VIEWER&#39;.
         * 
         * @return builder
         * 
         */
        public Builder role(Output<String> role) {
            $.role = role;
            return this;
        }

        /**
         * @param role The role that the user should have in the project. One of &#39;ADMIN&#39;, &#39;PROJECT*DEVELOPER&#39;, or &#39;PROJECT*VIEWER&#39;.
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            return role(Output.of(role));
        }

        /**
         * @param userId The ID of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
         * 
         * @return builder
         * 
         */
        public Builder userId(@Nullable Output<String> userId) {
            $.userId = userId;
            return this;
        }

        /**
         * @param userId The ID of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
         * 
         * @return builder
         * 
         */
        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        /**
         * @param username The username of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
         * 
         * @return builder
         * 
         */
        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The username of the user to add to the project. Exactly one of `userId`, `email`, or `username` must be specified.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public ProjectMembersMemberArgs build() {
            if ($.role == null) {
                throw new MissingRequiredPropertyException("ProjectMembersMemberArgs", "role");
            }
            return $;
        }
    }

}
