// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a Feature Flag SDK Key resource.
 *
 * SDK keys are project-scoped and environment-specific. Vercel only returns the cleartext SDK key and connection string at creation time, so this resource preserves the existing sensitive values in state when later reads omit them.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vercel from "@pulumiverse/vercel";
 *
 * const example = new vercel.Project("example", {name: "feature-flag-sdk-key-example"});
 * const exampleFeatureFlagSdkKey = new vercel.FeatureFlagSdkKey("example", {
 *     projectId: example.id,
 *     environment: "production",
 *     type: "server",
 *     label: "backend-sdk",
 * });
 * const exampleProjectEnvironmentVariable = new vercel.ProjectEnvironmentVariable("example", {
 *     projectId: example.id,
 *     targets: ["production"],
 *     sensitive: true,
 *     key: "FLAGS_CONNECTION_STRING",
 *     value: exampleFeatureFlagSdkKey.connectionString,
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * If importing into a personal account, or with a team configured on
 * the provider, simply use the project ID and SDK key hash.
 * - projectId can be found in the project `settings` tab in the Vercel UI.
 * - hashKey can be found from the Flags SDK Keys UI or API.
 *
 * ```sh
 * $ pulumi import vercel:index/featureFlagSdkKey:FeatureFlagSdkKey example prj_xxxxxxxxxxxxxxxxxxxxxxxxxxxx/sdk_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 * ```
 *
 * Alternatively, you can import via the team_id, project_id, and SDK key hash.
 * - teamId can be found in the team `settings` tab in the Vercel UI.
 * - projectId can be found in the project `settings` tab in the Vercel UI.
 *
 * ```sh
 * $ pulumi import vercel:index/featureFlagSdkKey:FeatureFlagSdkKey example team_xxxxxxxxxxxxxxxxxxxxxxxx/prj_xxxxxxxxxxxxxxxxxxxxxxxxxxxx/sdk_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 * ```
 */
export class FeatureFlagSdkKey extends pulumi.CustomResource {
    /**
     * Get an existing FeatureFlagSdkKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FeatureFlagSdkKeyState, opts?: pulumi.CustomResourceOptions): FeatureFlagSdkKey {
        return new FeatureFlagSdkKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vercel:index/featureFlagSdkKey:FeatureFlagSdkKey';

    /**
     * Returns true if the given object is an instance of FeatureFlagSdkKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FeatureFlagSdkKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FeatureFlagSdkKey.__pulumiType;
    }

    /**
     * The connection string for this SDK key. Vercel only returns this at creation time.
     */
    declare public /*out*/ readonly connectionString: pulumi.Output<string>;
    /**
     * The environment this SDK key should authenticate against.
     */
    declare public readonly environment: pulumi.Output<string>;
    /**
     * An optional label to help identify this key in the Vercel dashboard.
     */
    declare public readonly label: pulumi.Output<string | undefined>;
    /**
     * The ID of the Vercel project that owns the SDK key.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * The cleartext SDK key. Vercel only returns this at creation time.
     */
    declare public /*out*/ readonly sdkKey: pulumi.Output<string>;
    /**
     * The ID of the Vercel team. Required when configuring a team resource if a default team has not been set in the provider.
     */
    declare public readonly teamId: pulumi.Output<string>;
    /**
     * The SDK key type. Must be one of `server`, `mobile`, or `client`.
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a FeatureFlagSdkKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FeatureFlagSdkKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FeatureFlagSdkKeyArgs | FeatureFlagSdkKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FeatureFlagSdkKeyState | undefined;
            resourceInputs["connectionString"] = state?.connectionString;
            resourceInputs["environment"] = state?.environment;
            resourceInputs["label"] = state?.label;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["sdkKey"] = state?.sdkKey;
            resourceInputs["teamId"] = state?.teamId;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as FeatureFlagSdkKeyArgs | undefined;
            if (args?.environment === undefined && !opts.urn) {
                throw new Error("Missing required property 'environment'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["environment"] = args?.environment;
            resourceInputs["label"] = args?.label;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["type"] = args?.type;
            resourceInputs["connectionString"] = undefined /*out*/;
            resourceInputs["sdkKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["connectionString", "sdkKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(FeatureFlagSdkKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FeatureFlagSdkKey resources.
 */
export interface FeatureFlagSdkKeyState {
    /**
     * The connection string for this SDK key. Vercel only returns this at creation time.
     */
    connectionString?: pulumi.Input<string>;
    /**
     * The environment this SDK key should authenticate against.
     */
    environment?: pulumi.Input<string>;
    /**
     * An optional label to help identify this key in the Vercel dashboard.
     */
    label?: pulumi.Input<string>;
    /**
     * The ID of the Vercel project that owns the SDK key.
     */
    projectId?: pulumi.Input<string>;
    /**
     * The cleartext SDK key. Vercel only returns this at creation time.
     */
    sdkKey?: pulumi.Input<string>;
    /**
     * The ID of the Vercel team. Required when configuring a team resource if a default team has not been set in the provider.
     */
    teamId?: pulumi.Input<string>;
    /**
     * The SDK key type. Must be one of `server`, `mobile`, or `client`.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FeatureFlagSdkKey resource.
 */
export interface FeatureFlagSdkKeyArgs {
    /**
     * The environment this SDK key should authenticate against.
     */
    environment: pulumi.Input<string>;
    /**
     * An optional label to help identify this key in the Vercel dashboard.
     */
    label?: pulumi.Input<string>;
    /**
     * The ID of the Vercel project that owns the SDK key.
     */
    projectId: pulumi.Input<string>;
    /**
     * The ID of the Vercel team. Required when configuring a team resource if a default team has not been set in the provider.
     */
    teamId?: pulumi.Input<string>;
    /**
     * The SDK key type. Must be one of `server`, `mobile`, or `client`.
     */
    type: pulumi.Input<string>;
}
