// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides a Vercel KMS Issuer resource.
 *
 * > **Note:** Vercel KMS is currently in beta. Its resources, data sources, and the underlying API may change in backwards-incompatible ways in future releases of the provider.
 *
 * A KMS Issuer signs JSON Web Tokens (JWTs) and exposes a JWKS endpoint at
 * `https://kms.vercel.com/{id}/jwks.json`. An initial signing key is created
 * automatically; use `vercel.KmsSigningKey` to rotate keys and
 * `vercel.KmsProjectGrant` to grant projects the ability to sign tokens.
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * If importing into a personal account, or with a team configured on
 * the provider, simply use the issuer id.
 * - issuerId can be found via the vercel.KmsIssuer data source or the API.
 *
 * ```sh
 * $ pulumi import vercel:index/kmsIssuer:KmsIssuer example iss_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 * ```
 *
 * Alternatively, you can import via the teamId and issuer id.
 * - teamId can be found in the team `settings` tab in the Vercel UI.
 *
 * ```sh
 * $ pulumi import vercel:index/kmsIssuer:KmsIssuer example team_xxxxxxxxxxxxxxxxxxxxxxxx/iss_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 * ```
 */
export class KmsIssuer extends pulumi.CustomResource {
    /**
     * Get an existing KmsIssuer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KmsIssuerState, opts?: pulumi.CustomResourceOptions): KmsIssuer {
        return new KmsIssuer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vercel:index/kmsIssuer:KmsIssuer';

    /**
     * Returns true if the given object is an instance of KmsIssuer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KmsIssuer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KmsIssuer.__pulumiType;
    }

    /**
     * The signing algorithm to use for the issuer. Defaults to `RS512`. Changing this forces a new issuer to be created.
     */
    declare public readonly algorithm: pulumi.Output<string>;
    /**
     * The time the issuer was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * A PEM-encoded private key to import for the issuer. When provided, the issuer's origin becomes `external` and the algorithm is inferred from the key. Changing this forces a new issuer to be created. This value is never returned by the API and cannot be recovered on import.
     */
    declare public readonly importKey: pulumi.Output<string | undefined>;
    /**
     * The key ID (`kid`) to assign to the imported key. Only valid when `importKey` is set. Changing this forces a new issuer to be created.
     */
    declare public readonly importKeyId: pulumi.Output<string | undefined>;
    /**
     * Identifies the policy that manages this issuer, if any.
     */
    declare public /*out*/ readonly managedBy: pulumi.Output<string>;
    /**
     * The name of the issuer.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The origin of the issuer's key material, either `vercel` or `external`.
     */
    declare public /*out*/ readonly origin: pulumi.Output<string>;
    /**
     * The ID of the team that owns the issuer.
     */
    declare public /*out*/ readonly ownerId: pulumi.Output<string>;
    /**
     * The signing keys belonging to the issuer. Keys are created automatically and can be rotated with the `vercel.KmsSigningKey` resource.
     */
    declare public /*out*/ readonly signingKeys: pulumi.Output<outputs.KmsIssuerSigningKey[]>;
    /**
     * The ID of the team the issuer should be created under. Required when configuring a team resource if a default team has not been set in the provider.
     */
    declare public readonly teamId: pulumi.Output<string>;
    /**
     * The time the issuer was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a KmsIssuer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KmsIssuerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KmsIssuerArgs | KmsIssuerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KmsIssuerState | undefined;
            resourceInputs["algorithm"] = state?.algorithm;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["importKey"] = state?.importKey;
            resourceInputs["importKeyId"] = state?.importKeyId;
            resourceInputs["managedBy"] = state?.managedBy;
            resourceInputs["name"] = state?.name;
            resourceInputs["origin"] = state?.origin;
            resourceInputs["ownerId"] = state?.ownerId;
            resourceInputs["signingKeys"] = state?.signingKeys;
            resourceInputs["teamId"] = state?.teamId;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as KmsIssuerArgs | undefined;
            resourceInputs["algorithm"] = args?.algorithm;
            resourceInputs["importKey"] = args?.importKey ? pulumi.secret(args.importKey) : undefined;
            resourceInputs["importKeyId"] = args?.importKeyId;
            resourceInputs["name"] = args?.name;
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["managedBy"] = undefined /*out*/;
            resourceInputs["origin"] = undefined /*out*/;
            resourceInputs["ownerId"] = undefined /*out*/;
            resourceInputs["signingKeys"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["importKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(KmsIssuer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering KmsIssuer resources.
 */
export interface KmsIssuerState {
    /**
     * The signing algorithm to use for the issuer. Defaults to `RS512`. Changing this forces a new issuer to be created.
     */
    algorithm?: pulumi.Input<string>;
    /**
     * The time the issuer was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * A PEM-encoded private key to import for the issuer. When provided, the issuer's origin becomes `external` and the algorithm is inferred from the key. Changing this forces a new issuer to be created. This value is never returned by the API and cannot be recovered on import.
     */
    importKey?: pulumi.Input<string>;
    /**
     * The key ID (`kid`) to assign to the imported key. Only valid when `importKey` is set. Changing this forces a new issuer to be created.
     */
    importKeyId?: pulumi.Input<string>;
    /**
     * Identifies the policy that manages this issuer, if any.
     */
    managedBy?: pulumi.Input<string>;
    /**
     * The name of the issuer.
     */
    name?: pulumi.Input<string>;
    /**
     * The origin of the issuer's key material, either `vercel` or `external`.
     */
    origin?: pulumi.Input<string>;
    /**
     * The ID of the team that owns the issuer.
     */
    ownerId?: pulumi.Input<string>;
    /**
     * The signing keys belonging to the issuer. Keys are created automatically and can be rotated with the `vercel.KmsSigningKey` resource.
     */
    signingKeys?: pulumi.Input<pulumi.Input<inputs.KmsIssuerSigningKey>[]>;
    /**
     * The ID of the team the issuer should be created under. Required when configuring a team resource if a default team has not been set in the provider.
     */
    teamId?: pulumi.Input<string>;
    /**
     * The time the issuer was last updated.
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a KmsIssuer resource.
 */
export interface KmsIssuerArgs {
    /**
     * The signing algorithm to use for the issuer. Defaults to `RS512`. Changing this forces a new issuer to be created.
     */
    algorithm?: pulumi.Input<string>;
    /**
     * A PEM-encoded private key to import for the issuer. When provided, the issuer's origin becomes `external` and the algorithm is inferred from the key. Changing this forces a new issuer to be created. This value is never returned by the API and cannot be recovered on import.
     */
    importKey?: pulumi.Input<string>;
    /**
     * The key ID (`kid`) to assign to the imported key. Only valid when `importKey` is set. Changing this forces a new issuer to be created.
     */
    importKeyId?: pulumi.Input<string>;
    /**
     * The name of the issuer.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the team the issuer should be created under. Required when configuring a team resource if a default team has not been set in the provider.
     */
    teamId?: pulumi.Input<string>;
}
