// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides a Network resource.
 */
export class Network extends pulumi.CustomResource {
    /**
     * Get an existing Network resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkState, opts?: pulumi.CustomResourceOptions): Network {
        return new Network(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vercel:index/network:Network';

    /**
     * Returns true if the given object is an instance of Network.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Network {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Network.__pulumiType;
    }

    /**
     * The ID of the AWS Account in which the network exists.
     */
    declare public /*out*/ readonly awsAccountId: pulumi.Output<string>;
    /**
     * The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
     */
    declare public readonly awsAvailabilityZoneIds: pulumi.Output<string[]>;
    /**
     * The AWS Region in which the network exists.
     */
    declare public /*out*/ readonly awsRegion: pulumi.Output<string>;
    /**
     * The CIDR range of the Network.
     */
    declare public readonly cidr: pulumi.Output<string>;
    /**
     * The egress IP addresses of the Network.
     */
    declare public /*out*/ readonly egressIpAddresses: pulumi.Output<string[]>;
    /**
     * The name of the network.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The Vercel region in which the Network exists.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The status of the Network.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
     */
    declare public readonly teamId: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.NetworkTimeouts | undefined>;
    /**
     * The ID of the AWS VPC which hosts the network.
     */
    declare public /*out*/ readonly vpcId: pulumi.Output<string>;

    /**
     * Create a Network resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkArgs | NetworkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkState | undefined;
            resourceInputs["awsAccountId"] = state?.awsAccountId;
            resourceInputs["awsAvailabilityZoneIds"] = state?.awsAvailabilityZoneIds;
            resourceInputs["awsRegion"] = state?.awsRegion;
            resourceInputs["cidr"] = state?.cidr;
            resourceInputs["egressIpAddresses"] = state?.egressIpAddresses;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
            resourceInputs["status"] = state?.status;
            resourceInputs["teamId"] = state?.teamId;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["vpcId"] = state?.vpcId;
        } else {
            const args = argsOrState as NetworkArgs | undefined;
            if (args?.cidr === undefined && !opts.urn) {
                throw new Error("Missing required property 'cidr'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["awsAvailabilityZoneIds"] = args?.awsAvailabilityZoneIds;
            resourceInputs["cidr"] = args?.cidr;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["awsAccountId"] = undefined /*out*/;
            resourceInputs["awsRegion"] = undefined /*out*/;
            resourceInputs["egressIpAddresses"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["vpcId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Network.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Network resources.
 */
export interface NetworkState {
    /**
     * The ID of the AWS Account in which the network exists.
     */
    awsAccountId?: pulumi.Input<string>;
    /**
     * The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
     */
    awsAvailabilityZoneIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The AWS Region in which the network exists.
     */
    awsRegion?: pulumi.Input<string>;
    /**
     * The CIDR range of the Network.
     */
    cidr?: pulumi.Input<string>;
    /**
     * The egress IP addresses of the Network.
     */
    egressIpAddresses?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the network.
     */
    name?: pulumi.Input<string>;
    /**
     * The Vercel region in which the Network exists.
     */
    region?: pulumi.Input<string>;
    /**
     * The status of the Network.
     */
    status?: pulumi.Input<string>;
    /**
     * The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
     */
    teamId?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.NetworkTimeouts>;
    /**
     * The ID of the AWS VPC which hosts the network.
     */
    vpcId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Network resource.
 */
export interface NetworkArgs {
    /**
     * The IDs of the AWS Availability Zones in which the network exists, if specified during creation.
     */
    awsAvailabilityZoneIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The CIDR range of the Network.
     */
    cidr: pulumi.Input<string>;
    /**
     * The name of the network.
     */
    name?: pulumi.Input<string>;
    /**
     * The Vercel region in which the Network exists.
     */
    region: pulumi.Input<string>;
    /**
     * The unique identifier of the Team that owns the Network. Required when configuring a team resource if a default team has not been set in the provider.
     */
    teamId?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.NetworkTimeouts>;
}
