// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Creates and manages a Deployment Check for a Vercel project.
 *
 * This resource manages a project-level check definition. It does not execute tests, create a GitHub workflow or webhook endpoint, or report check-run results. Configure the corresponding GitHub workflow, external runner, or integration separately.
 *
 * ## Example Usage
 *
 * ### GitHub and webhook checks
 *
 * Use a Vercel access token authorized for the project. GitHub checks currently support only `github`; `externalCheckName` must match the check reported by the workflow. GitHub checks cannot be rerequestable through Vercel.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vercel from "@pulumiverse/vercel";
 *
 * const config = new pulumi.Config();
 * // GitHub repository connected to Vercel, in owner/repository format.
 * const githubRepository = config.require("githubRepository");
 * const example = new vercel.Project("example", {
 *     name: "deployment-checks-example",
 *     gitRepository: {
 *         type: "github",
 *         repo: githubRepository,
 *     },
 * });
 * // The external check name must match the check reported by your GitHub workflow.
 * // This resource registers a gate; it does not create or run the workflow.
 * const e2e = new vercel.ProjectDeploymentCheck("e2e", {
 *     projectId: example.id,
 *     name: "End-to-end tests",
 *     requires: "deployment-url",
 *     blocks: "deployment-alias",
 *     targets: ["production"],
 *     isRerequestable: false,
 *     source: {
 *         kind: "git-provider",
 *         provider: "github",
 *         externalCheckName: "e2e",
 *     },
 * });
 * // A webhook-backed check for an external test runner. The runner must handle
 * // check events and report results through the Checks API separately.
 * const webhook = new vercel.ProjectDeploymentCheck("webhook", {
 *     projectId: example.id,
 *     name: "External smoke tests",
 *     requires: "deployment-url",
 *     blocks: "none",
 *     targets: ["preview"],
 *     isRerequestable: true,
 *     source: {
 *         kind: "webhook",
 *     },
 * });
 * ```
 *
 * ### Integration checks
 *
 * Integration checks require an integration installation token. The API identifies the integration and installation from that token. Use this token only with an `integration` source because it determines the returned source kind. The optional `externalResourceId` must belong to that installation.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vercel from "@pulumiverse/vercel";
 *
 * const config = new pulumi.Config();
 * // An integration installation token authorized for this project.
 * const integrationToken = config.require("integrationToken");
 * // The ID or name of an existing project accessible to the integration.
 * const projectId = config.require("projectId");
 * // The team that owns the project.
 * const teamId = config.require("teamId");
 * const integration = new vercel.ProjectDeploymentCheck("integration", {
 *     projectId: projectId,
 *     name: "Integration quality gate",
 *     requires: "build-ready",
 *     blocks: "deployment-alias",
 *     targets: ["production"],
 *     source: {
 *         kind: "integration",
 *     },
 * });
 * ```
 *
 * ## Choosing check behavior
 *
 * - `requires` selects when the check can run: `build-ready`, `deployment-url`, or `none`.
 * - `blocks = "deployment-alias"` gates domain assignment; `blocks = "none"` makes the check non-blocking. Omission uses the API default, `deployment-alias`.
 * - `targets` accepts `production`, `preview`, or custom environment IDs (not slugs). For a custom environment managed by Terraform, use `targets = [vercel_custom_environment.staging.id]`. Omission defaults to production. Use `["all"]` to select every environment; do not combine `all` with other targets or supply an empty set.
 * - `isRerequestable` defaults to false. Enable it only when your webhook runner or integration handles rerun requests.
 * - Optional computed settings are populated from the API. Omitting a previously configured setting keeps its current value; it does not reset the setting to its creation default.
 *
 * Changing `projectId`, an explicitly configured `teamId`, or a configured source field replaces the check. Changing `requires` to `none` also replaces it because the API does not support that PATCH operation. Other supported settings update in place. Replacement deletes the old check and creates a new check with a new ID.
 *
 * ## Import
 *
 * Use `team_id/project_id/check_id`, or `project_id/check_id` when the provider supplies the team. Project names are supported; the imported identifier must match the `projectId` value in configuration to avoid replacement.
 *
 * With an explicit team:
 *
 * ```sh
 * $ pulumi import vercel:index/projectDeploymentCheck:ProjectDeploymentCheck e2e team_xxx/prj_xxx/check_xxx
 * ```
 *
 * With the team configured on the provider:
 *
 * ```sh
 * $ pulumi import vercel:index/projectDeploymentCheck:ProjectDeploymentCheck e2e prj_xxx/check_xxx
 * ```
 *
 * Project names are also supported. Use the same ID or name as projectId in config.
 *
 * ```sh
 * $ pulumi import vercel:index/projectDeploymentCheck:ProjectDeploymentCheck e2e team_xxx/my-project/check_xxx
 * ```
 *
 * For Terraform 1.5 and later:
 *
 * Match `name` and `requires` to the existing check before applying. Omit `source` to preserve an imported source, including Vercel-managed checks and Git-provider variants that this resource cannot create. Likewise, omit `blocks` to preserve an API value outside the configurable `deployment-alias` and `none` values. Inspect the imported state with `terraform state show` before configuring additional fields.
 *
 * A source is required for new checks. For an imported check with an omitted source, configuring a different source replaces it. Supply a writable source before changing `requires` to `none`; response-only sources cannot be recreated by this resource.
 */
export class ProjectDeploymentCheck extends pulumi.CustomResource {
    /**
     * Get an existing ProjectDeploymentCheck resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectDeploymentCheckState, opts?: pulumi.CustomResourceOptions): ProjectDeploymentCheck {
        return new ProjectDeploymentCheck(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vercel:index/projectDeploymentCheck:ProjectDeploymentCheck';

    /**
     * Returns true if the given object is an instance of ProjectDeploymentCheck.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectDeploymentCheck {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectDeploymentCheck.__pulumiType;
    }

    /**
     * The deployment stage blocked by the check. New checks currently support `deployment-alias` and `none`.
     */
    declare public readonly blocks: pulumi.Output<string>;
    /**
     * Whether users can rerun the check. Defaults to false; must be false for a `git-provider` source.
     */
    declare public readonly isRerequestable: pulumi.Output<boolean>;
    /**
     * The human-readable name of the Deployment Check.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID or name of the Vercel project.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * The deployment stage required before the check runs: `build-ready`, `deployment-url`, or `none`. Changing this to `none` replaces the check because the API does not support that update.
     */
    declare public readonly requires: pulumi.Output<string>;
    /**
     * The system that supplies the Deployment Check. Required when creating a check; changing a configured source field replaces the check. Omit it when managing an imported check whose source is not writable through the API.
     */
    declare public readonly source: pulumi.Output<outputs.ProjectDeploymentCheckSource>;
    /**
     * Deployment environments to which the check applies: `production`, `preview`, or a custom environment ID. Use `["all"]` for every environment; `all` cannot be combined with other targets. The API defaults to `["production"]`.
     */
    declare public readonly targets: pulumi.Output<string[]>;
    /**
     * The ID of the Vercel team.
     */
    declare public readonly teamId: pulumi.Output<string>;
    /**
     * The timeout value supplied to check runners by the Checks API. When omitted, the API determines the value.
     */
    declare public readonly timeout: pulumi.Output<number>;

    /**
     * Create a ProjectDeploymentCheck resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectDeploymentCheckArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectDeploymentCheckArgs | ProjectDeploymentCheckState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectDeploymentCheckState | undefined;
            resourceInputs["blocks"] = state?.blocks;
            resourceInputs["isRerequestable"] = state?.isRerequestable;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["requires"] = state?.requires;
            resourceInputs["source"] = state?.source;
            resourceInputs["targets"] = state?.targets;
            resourceInputs["teamId"] = state?.teamId;
            resourceInputs["timeout"] = state?.timeout;
        } else {
            const args = argsOrState as ProjectDeploymentCheckArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.requires === undefined && !opts.urn) {
                throw new Error("Missing required property 'requires'");
            }
            resourceInputs["blocks"] = args?.blocks;
            resourceInputs["isRerequestable"] = args?.isRerequestable;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["requires"] = args?.requires;
            resourceInputs["source"] = args?.source;
            resourceInputs["targets"] = args?.targets;
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["timeout"] = args?.timeout;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectDeploymentCheck.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProjectDeploymentCheck resources.
 */
export interface ProjectDeploymentCheckState {
    /**
     * The deployment stage blocked by the check. New checks currently support `deployment-alias` and `none`.
     */
    blocks?: pulumi.Input<string>;
    /**
     * Whether users can rerun the check. Defaults to false; must be false for a `git-provider` source.
     */
    isRerequestable?: pulumi.Input<boolean>;
    /**
     * The human-readable name of the Deployment Check.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID or name of the Vercel project.
     */
    projectId?: pulumi.Input<string>;
    /**
     * The deployment stage required before the check runs: `build-ready`, `deployment-url`, or `none`. Changing this to `none` replaces the check because the API does not support that update.
     */
    requires?: pulumi.Input<string>;
    /**
     * The system that supplies the Deployment Check. Required when creating a check; changing a configured source field replaces the check. Omit it when managing an imported check whose source is not writable through the API.
     */
    source?: pulumi.Input<inputs.ProjectDeploymentCheckSource>;
    /**
     * Deployment environments to which the check applies: `production`, `preview`, or a custom environment ID. Use `["all"]` for every environment; `all` cannot be combined with other targets. The API defaults to `["production"]`.
     */
    targets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the Vercel team.
     */
    teamId?: pulumi.Input<string>;
    /**
     * The timeout value supplied to check runners by the Checks API. When omitted, the API determines the value.
     */
    timeout?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a ProjectDeploymentCheck resource.
 */
export interface ProjectDeploymentCheckArgs {
    /**
     * The deployment stage blocked by the check. New checks currently support `deployment-alias` and `none`.
     */
    blocks?: pulumi.Input<string>;
    /**
     * Whether users can rerun the check. Defaults to false; must be false for a `git-provider` source.
     */
    isRerequestable?: pulumi.Input<boolean>;
    /**
     * The human-readable name of the Deployment Check.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID or name of the Vercel project.
     */
    projectId: pulumi.Input<string>;
    /**
     * The deployment stage required before the check runs: `build-ready`, `deployment-url`, or `none`. Changing this to `none` replaces the check because the API does not support that update.
     */
    requires: pulumi.Input<string>;
    /**
     * The system that supplies the Deployment Check. Required when creating a check; changing a configured source field replaces the check. Omit it when managing an imported check whose source is not writable through the API.
     */
    source?: pulumi.Input<inputs.ProjectDeploymentCheckSource>;
    /**
     * Deployment environments to which the check applies: `production`, `preview`, or a custom environment ID. Use `["all"]` for every environment; `all` cannot be combined with other targets. The API defaults to `["production"]`.
     */
    targets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the Vercel team.
     */
    teamId?: pulumi.Input<string>;
    /**
     * The timeout value supplied to check runners by the Checks API. When omitted, the API determines the value.
     */
    timeout?: pulumi.Input<number>;
}
